### ISSUE TITLE
[Feature Request] Ability to add Tag

### ISSUE THREAD

**Issue by jfishie** [revenz/FileFlows#100]
Request for an additional FFmpeg Builder Node to be added to allow users to add tags to files.

For instance, macOS users may want to add the "-tag:v hvc1" command to H265 files which allows the files to preview in macOS Finder or play in QuickTime.

**Comment by revenz** [comment]
added this node

https://docs.fileflows.com/plugins/video-nodes/ffmpeg-builder/video-tag

**Comment by jfishie** [comment]
I will try again this evening but I was not able to see this node after updating through the interface as well as pulling the latest docker  image.

**Comment by revenz** [comment]
next version
