### ISSUE TITLE
[Feature Request] Ability to filter by coded tag string

### ISSUE THREAD

**Issue by jfishie** [revenz/FileFlows#101]
Looking for the ability to filter files by codec "tag" string instead of actual codec.

This feature request goes hand in hand with #100 to add a FFmpeg Builder node to add tags to files. 

The current "Video Has Stream" node looks a the codec type not the tag so files cannot be filtered into different flows.

**Comment by revenz** [comment]
Can you get me a sample file with a tag in it like you want?

I tried all my test files but none have one.

**Comment by jfishie** [comment]
Will this work? [https://www.dropbox.com/s/2nycx9wzbhmg7qi/IMG_1305.mp4?dl=0](url)

If you could let me know when you have the file I would like to take the link down.

**Comment by revenz** [comment]
Downloaded it, but dont see any tags on it

Output from ffmpeg 
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\videos\testfiles\tag.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.45.100
  Duration: 00:00:10.91, start: 0.000000, bitrate: 15601 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, progressive), 3840x2160, 15520 kb/s, 60 fps, 60 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
At least one output file must be specified

```

Opening in VLC doesn't show anything either

**Comment by jfishie** [comment]
This is output from tdarr.

I did some googling and believe I found that HVC1 has been changed to HEV1


This is the output from a file converted in Tdarr with the tag "-tag:v hvc1" added to the ffmpeg command. Perhaps I am not referring to it properly but I see HVC1 in Stream #0 for your post above. Everything that I have come across states that the HVC1 tag is required to get quick preview working in macOS and I can apply it but am not how to filter it our in FileFlows. 

}
"ffProbeData":{
"streams":[
0:{
"index":0
"codec_name":"hevc"
"codec_long_name":"H.265 / HEVC (High Efficiency Video Coding)"
"profile":"Main"
"codec_type":"video"
"codec_tag_string":"hvc1"
"codec_tag":"0x31637668"
"width":3840

**Comment by jfishie** [comment]
I see the information I would like to filter against in the fileflows log when using the "Video File" or "Read File Info" nodes. Stream zero displays hvc1 when the information is read but only outputs the codec (hevc). Perhaps I am not using the correct language when referring to it as the tag.

Fileflows log

>  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.16.100
  Duration: 00:01:33.60, start: 0.000000, bitrate: 1134 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, progressive), 320x240 [SAR 1:1 DAR 4:3], 995 kb/s, 15 fps, 15 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Audio: mp3 (mp4a / 0x6134706D), 22050 Hz, mono, fltp, 59 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
2022-06-25 03:38:03.009 - INFO -> Video stream duration: 00:01:33.6000000
2022-06-25 03:38:03.032 - INFO -> Video stream 'hevc' '0'
2022-06-25 03:38:03.033 - INFO -> Audio stream 'aac' '1' '
2022-06-25 03:38:03.033 - INFO -> Audio stream 'mp3' '2' '
2022-06-25 03:38:03.038 - DBUG -> output: 1
2022-06-25 03:38:03.039 - DBUG -> flow completed
2022-06-25 03:38:03.040 - DBUG -> flow completed 1
2022-06-25 03:38:03.040 - DBUG -> flow status set to processed

**Comment by jfishie** [comment]
Can either node read and return the whole string for a given stream or only the main codec?

**Comment by revenz** [comment]
added CodecTag to video stream and Video Has Stream now uses this when checking codecs aswell
