### ISSUE TITLE
'Auto Update' being enabled in Docker causes container to stop on attempted update

### ISSUE THREAD

**Issue by SkippyTheIdiot** [revenz/FileFlows#102]
Not really unexpected behaviour, but there should probably be a warning or outright disable the option when in a docker container.

**Comment by revenz** [comment]
Why?  This is how I update my docker install, do it every dev build. 

Just set your docker container to auto restart.

**Comment by SkippyTheIdiot** [comment]
I've been using FileFlows on Unraid, and auto-restart isn't a setting exposed in UI, and I suggest adding `--restart unless-stopped` to the extra parameters on the Unraid template.

It's also generally bad practice to update internal docker container data. For dev builds, not really a major concern, but for stable deployments, it's generally not a good idea.

**Comment by revenz** [comment]
If you don't think its a good idea, then turn it off.   But for this type of app and how its deployed.  its perfectly fine.   
The docker doesn't build the application, its prebuilt, so downloading an update is the exact same as a new docker build.

By exposing auto update, the end user doesnt need to do anything.  automatically download a version online, then any node also get automatically updated.

But its a setting, you can turn it off.

I'll update the template with unless-stopped for unraid.

**Comment by revenz** [comment]
Actually, these were already set to restart unless stopped.  I changed these a while ago.

**Comment by SkippyTheIdiot** [comment]
My apologies for my ignorance, a series of unfortunate coincidences led me to that specific train of thought.

Working with docker myself, I tend toward building an app into the docker container for simplicity and honestly forgot that isn't the only way of doing things.

I did a hard switch away from Tdarr some time ago, as it was causing more trouble than it was worth, and this has been the only issue I've had with FileFlows and it was slowly driving me mad.

**Comment by revenz** [comment]
no worries
