### ISSUE TITLE
[Feature Request] More robust library statistics

### ISSUE THREAD

**Issue by jfishie** [revenz/FileFlows#104]
It would be nice to have additional statistics about each library or overall sum of all libraries.

An alphanumeric and visual representation of library metrics such as

- size (old and new)
- space saved
- number and name of codecs used (audio and video) etc. 

All of these help users visualize how much work has been completed and how much needs to be completed.

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/173171398-9d16a3d3-e46d-4b29-868c-c40c490578d6.png)
Already shows some of this info
- space saved + number of items

Showing things like codecs that's a different matter.   how fileflows is designed, it doesn't know what a codec is, that comes from the "Video Nodes" plugin.

I need to implement a generic statistics reporting that plugins can push additional data into and then, have reports that query that data.

**Comment by reavessm** [comment]
I just want to throw in that you can't see that information from mobile.  Having the statistics always visible on the side/bottom would make the UI more portable and accessible.

**Comment by revenz** [comment]
done in 0.8.3
