### ISSUE TITLE
Set subtitle language 

### ISSUE THREAD

**Issue by Yankees4life** [revenz/FileFlows#107]
Hello

I would like a node to set the subtitle language. Some anime cappers don't set the subtitle language causing the ffmpeg builder to delete it even if it's what you desire

Pls and thank you

**Comment by revenz** [comment]
Updated "FFMPEG Builder: Audio Set Language" to support subtitles, and renamed to "FFMPEG Builder: Set Language"

https://docs.fileflows.com/plugins/video-nodes/ffmpeg-builder/set-language
