### ISSUE TITLE
Ability to delete image streams

### ISSUE THREAD

**Issue by Yankees4life** [revenz/FileFlows#110]
Some anime cappers tend to insert image streams in their mkv files which may affect media server's ability to stream it and inflates the file unnecessarily. Removing it would be useful as it serves no purpose other than waste a space in the file.

**Comment by revenz** [comment]
Updated this node (was "FFMPEG Builder: Audio Track Remover" to support audio/subtitle/videos

Images are treated as a video track in FFMPEG

https://docs.fileflows.com/plugins/video-nodes/ffmpeg-builder/track-remover

To remove images set to video and index 1.  That will keep the first video and remove the rest (ie the pictures)

I will improve upon this in the metadata removal node to make it easier for a user to understand.
