### ISSUE TITLE
temp folder cleanup not running.

### ISSUE THREAD

**Issue by jbiancam1** [revenz/FileFlows#111]
Temp folder cleanup job seems to not running.
I had runner files from a week or so back when I installed the program.

I'm running fileflows on a dockerized virtual machine setup of ubuntu server through proxmox.
Not sure if/what you need from me. If anything.

**Comment by iamwoz** [comment]
I've got some stuff in /temp as well although its older than my most recent processing. Will manually clear it out and see if anything lingers.

Looks like a couple could be orphans from when I changed my docker PID and GID.

![image](https://user-images.githubusercontent.com/85816876/174054101-f47e8012-34d5-4532-906e-bcbc0d1f1c6c.png)

**Comment by revenz** [comment]
Fixed in 0.8.1
