### ISSUE TITLE
[Bug] If "Video File" node at start of flow has error detecting video stream it ends in success

### ISSUE THREAD

**Issue by jbiancam1** [revenz/FileFlows#113]
"Video File" node exits with 0 and counts file as successfully processed when the log shows there was an error parsing it. It doesn't even hit the "Video Has Stream" node if there is no video stream at the start. I've had this same error with other files later on during ffmpeg executor and it triggers a flow failure. 
Ironically, In this particular case the file in question is actually the only one from that series that was completely broken, the rest had a different issue I could fix, and it is the only one that "Succeeded" initially. Below is the entire log after after the plugins downloaded lines.

`2022-06-16 22:11:11.815 - INFO -> Executing Node 1: VideoFile`
`2022-06-16 22:11:11.816 - INFO ->`
`======================================================================`
`2022-06-16 22:11:11.820 - INFO -> Making request[GET]: http://localhost:5000/api/tool/name/FFMpeg`
`2022-06-16 22:11:11.896 - INFO -> Video Information:`
`[matroska,webm @ 0x564c7fd3c500] Format matroska,webm detected only with low score of 1, misdetection possible!`
`[matroska,webm @ 0x564c7fd3c500] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number`
`[matroska,webm @ 0x564c7fd3c500] EBML header parsing failed`
`/media/Series/filename.mkv: Invalid data found when processing input`
`2022-06-16 22:11:11.900 - INFO -> No video streams detected.`
`2022-06-16 22:11:16.319 - INFO -> Connection_Closed`
`2022-06-16 22:11:17.257 - INFO -> Final Fingerprint: a993f8c574e0fea8c1cdcbcd9408d9e2e107ee6e4d120edcfa11decd53fa0cae`
`2022-06-16 22:11:17.257 - INFO -> Original Size: 246090998`
`2022-06-16 22:11:17.258 - INFO -> Final Size: 246090998`
`2022-06-16 22:11:17.259 - INFO -> Output Path: /media/Series/seriesname/Season 01/filename.mkv`
`2022-06-16 22:11:17.260 - INFO -> Final Status: Processed`
`2022-06-16 22:11:17.261 - INFO -> Making request[POST]: http://localhost:5000/api/worker/work/finish`
`2022-06-16 22:11:18.987 - INFO -> Exit Code: 0`

**Comment by revenz** [comment]
fixed
