### ISSUE TITLE
0.8.1.1448 web access issue

### ISSUE THREAD

**Issue by ray73864** [revenz/FileFlows#116]
Have just updated my server to have the latest version of FileFlows, but now I can no longer access the webui for it.

Have tried accessing the webui from localhost itself, and also from my PC, both come back saying they can't find the FileFlows server.

FileFlows is running on the remote host (A machine on my local network), windows firewall is disabled on it.

**Comment by revenz** [comment]
need the logs

**Comment by ray73864** [comment]
[FileFlows-Jun18-01.log](https://github.com/revenz/FileFlows/files/8931547/FileFlows-Jun18-01.log)

Had to add a .log to it so that github would allow it to be updated.

Prior to 4.52am (Western Australian Standard Time) is the previous version.

**Comment by revenz** [comment]
shouldnt take that long, to do an upgrade.   but yeah without the log of the actual problem no way of knowing.

glad its working
