### ISSUE TITLE
Node Request: Video Encode - option to copy (certain) subtitles as well

### ISSUE THREAD

**Issue by Yankees4life** [revenz/FileFlows#12]
The Video Encode node only has Video and audio options so I think subtitle option should be included too (and obviously allow a certain language to be kept too)

**Comment by revenz** [comment]
ive added "Subtitle Language Remover" node.

![image](https://user-images.githubusercontent.com/958400/160230536-15e968ff-dc99-4e57-abf6-63c1ed5fd07d.png)

Does this meet your requirements?

**Comment by Yankees4life** [comment]
That's good but I think there should be one for audio as well

**Comment by revenz** [comment]
thats already added aswell
![image](https://user-images.githubusercontent.com/958400/160269404-5e420b7c-efd7-4271-9ff8-a7d3d383b255.png)
