### ISSUE TITLE
[Bug] Flow zoom out keeps cursor drag select to default bounds

### ISSUE THREAD

**Issue by jbiancam1** [revenz/FileFlows#129]
<img width="677" alt="flowzoomout" src="https://user-images.githubusercontent.com/102190214/174607267-0f1f2c0e-3c84-4cbf-b5d4-1fd7b76e3b35.PNG">
When I zoom out the flow(100%-50%) it seems to keep the cursor click drag selecting bounds to the original size box. In the attached image I started my cursor at the very top right corner on 50% but the selection box is where it would be if I was back at 100%.

**Comment by revenz** [comment]
fixed
