### ISSUE TITLE
Rename "Pattern Replacer" to "Filename Pattern Replacer"

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#131]
Currently, this node is confusing as to what it does.

It replaces patterns in a filename and renames the file.

So rename it and make it more clear.

**Comment by Sprooty** [comment]
Raven, can you please make sure the descriptions/info around this are also updated to provide examples.

**Comment by revenz** [comment]
yes I'll write a pager on docs.fileflows.com for it.  been doing this for nodes as I update them.

This node is an early node and wasn't used much.

**Comment by revenz** [comment]
done in 0.8.2.306
help page https://docs.fileflows.com/plugins/basic-nodes/filename-pattern-replacer
