### ISSUE TITLE
[Bug] Nodes not presenting to server (including internal node)

### ISSUE THREAD

**Issue by reavessm** [revenz/FileFlows#134]
I have 1 container running the server and 3 containers running the nodes, all on the same container version, but the nodes keep looping with the following message:

```
Info -> Triggering worker: FlowWorker
2022-06-21 11:42:08.131 [INFO] -> Triggering worker: FlowWorker
Info -> Making request[GET]: https://fileflows.domain.com/api/node/by-address/fileflows-nodes-6zm4x?version=0.8.2.1469
2022-06-21 11:42:08.142 [INFO] -> Making request[GET]: https://fileflows.domain.com/api/node/by-address/fileflows-nodes-6zm4x?version=0.8.2.1469
Info -> Making request[GET]: https://fileflows.domain.com/api/system/version
2022-06-21 11:42:08.181 [INFO] -> Making request[GET]: https://fileflows.domain.com/api/system/version
```

Nodes have the following env:

```yaml
          env:
            - name: ServerUrl
              value: 'https://fileflows.domain.com'
            - name: FFNODE
              value: '1'
```

Server is looping with the following message:

```Info -> Triggering worker: FlowRunnerMonitor
2022-06-21 11:48:05.455 [INFO] -> Triggering worker: FlowRunnerMonitor
Debug -> Node 'Internal Processing Node' is not enabled
```

Here's what I'm seeing in the 'Nodes' tab in the UI:

![image](https://user-images.githubusercontent.com/23387932/174792379-9705a549-f41c-4a62-bbb9-24a693930aed.png)

I'm not really sure how to proceed with this error.

**Comment by revenz** [comment]
you just replaced your actual server url with "https://fileflows.domain.com'" for posting here right?

**Comment by reavessm** [comment]
Yes.  The actual url points to the server address and its a domain that I control.  The config was working, but it broke around the time #98 was added.  I added the new ENV variables to test the, but even after removing them it still won't connect.

**Comment by revenz** [comment]
can you post the full log from the node and the server?

**Comment by revenz** [comment]
closing as no follow up
