### ISSUE TITLE
[Request] Copy Node - Copy all files function behaviour when files are in child directory

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#140]
Relevant logs where this scenario occurs can be found on https://github.com/revenz/FileFlows/issues/139

- Movie file is in child directory eg,  _\Movies\6.Days.2017.1080p.BluRay.x264-PSYCHD\6.days.2017.1080p.bluray.x264-psychd\6.Days.2017.1080p.BluRay.x264-PSYCHD.mkv_
- The "copy all files" function copy does not copy all the files from the parent directory

This is likely expected behavior, but I'm not sure it can be guaranteed that all users will be using a flat file structure as potentially assumed
![Original_Movie](https://user-images.githubusercontent.com/4150588/175761851-9ddd6581-ff73-48ec-bdd5-d8ed5ca16273.jpg)
![FileFlows Output](https://user-images.githubusercontent.com/4150588/175761858-5d4208ae-c867-4d07-912b-73fab0f085aa.jpg)

![Original_Root](https://user-images.githubusercontent.com/4150588/175761847-82cbd1f7-b51f-4c9c-bc39-8ec931da365f.jpg)
.

**Comment by revenz** [comment]
Definitely not a bug, and by design.

Work around would be to move the file to the parent directory.  Then to copy files to a new directory.  That way you would pickup the additional files.
Out of those files what do you want to keep though, Subs I get, the rest are just rubbish files.

**Comment by revenz** [comment]
is this still required?

**Comment by Sprooty** [comment]
Closing as not a bug
