### ISSUE TITLE
[Bug] Libraries screen - "Flows" not updating Flow name when flow name is changed

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#147]
- Create Flow
- Create Library and attach flow
- Edit flow and change name
- Library screen shows old flow name; 
- Edit library to change flow, note correct Flow name is used already in edit drop down, saving does not update the library screen
![SNAG-0003 26-06-2022 7 58 42 PM](https://user-images.githubusercontent.com/4150588/175809054-70a2aa53-bca4-489b-8c76-0df35b721623.jpg)
![SNAG-0002 26-06-2022 7 58 33 PM](https://user-images.githubusercontent.com/4150588/175809058-1dfed0fc-1556-49ef-bfc2-2305d864054a.jpg)
![SNAG-0001 26-06-2022 7 58 17 PM](https://user-images.githubusercontent.com/4150588/175809059-99b57232-681b-4c0c-9259-aee2253f26f9.jpg)
.

**Comment by revenz** [comment]
known issue, fix

Create worker that updates ObjectReferences.   Create a stored procedure to update object references when saved

**Comment by revenz** [comment]
worker now runs at 1am, and whenever a library or flow is renamed, updater is also run
