### ISSUE TITLE
Failed to create CoreCLR - Unraid Docker

### ISSUE THREAD

**Issue by BenSanborn** [revenz/FileFlows#148]
Hi, tried to set this up server on unRAID, the UI won't resolve and logs are filled with this:

Launching server
Failed to create CoreCLR, HRESULT: 0x80070008

![Screenshot 2022-06-26 113210](https://user-images.githubusercontent.com/8119804/175821782-6f02adec-e0e7-40eb-b1d9-ff2bbc1475a4.png)

Please see attached pic
![Screenshot 2022-06-26 113153](https://user-images.githubusercontent.com/8119804/175821781-49dc8044-714a-424f-aa66-900295446adb.png)

![Screenshot 2022-06-26 113136](https://user-images.githubusercontent.com/8119804/175821777-7fff9ef5-c3fb-4eb6-8228-d8f8d6de830d.png)
s

**Comment by revenz** [comment]
just tried pulling the latest docker image and create a fresh install on unraid, and worked fine for me.

can you delete the app and recreate it with the latest image?

**Comment by BenSanborn** [comment]
Hey revenz, still didn't work.

Have anything to do with my unRAID version by chance? I'm on 6.9.1.

![image](https://user-images.githubusercontent.com/8119804/175833250-a3b267e0-0651-4f64-8036-ee4fc4347e2d.png)

![image](https://user-images.githubusercontent.com/8119804/175833269-83a74b16-a700-4c82-b8e1-2d699df669cf.png)

**Comment by revenz** [comment]
Doubt it... but I am on 6.9.2

**Comment by BenSanborn** [comment]
Updated unRAID to 6.10.3 and it magically works now.

I've also seen YT tutorials start at 6.9.2, maybe write somewhere that it's the base unRAID version required, haha.

Thank you for the assistance and can't wait to try it out revenz!

**Comment by revenz** [comment]
no worries, good to know its fixed.
