### ISSUE TITLE
File ordering or randomising selection to process.

### ISSUE THREAD

**Issue by nicgentile** [revenz/FileFlows#153]
I have faced a problem. I am processing many files on many drives. Likewise, I can add the libraries, no problem, but if I run multiple flows, they do things sequentially from the same drive, so other drives are sitting idle, while the one drives takes a beating. I am trying to process one ffmpeg instance to one drive. How may I achieve this?

**Comment by revenz** [comment]
this is already implemented but requires MySQL to be used as it's done in a stored procedure.  meaning it's a paid feature.

**Comment by nicgentile** [comment]
Cool.
