### ISSUE TITLE
[Suggestion] Files paging last page navigatable. 

### ISSUE THREAD

**Issue by jbiancam1** [revenz/FileFlows#163]
This is obviously low priority. 
It would be nice if the files paging tabs had the last page as one of the option to navigate to if there are more than the default 15. With 26k in the processing and the page size set to 500 it takes me 7 clicks and nearly 30 seconds of loading to get to the end. I like to make sure the stuff I'm replacing has been added.
Something like this may be helpful for people with larger libraries.
<img width="386" alt="paging" src="https://user-images.githubusercontent.com/102190214/176966137-94881baa-d8e8-44da-88e4-dfc64452ea7b.PNG">
Inspect element mockup worked better than I expected.

**Comment by revenz** [comment]
![Image](https://user-images.githubusercontent.com/958400/177021578-9f982e18-1ab3-4c16-9633-4b8c969a6b22.png)

done
