### ISSUE TITLE
[Bug] Reordering subtitles results in wrong order/language

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#165]
Before: 
English (with english content)
German (with german content)
After:
German (with english content)
English (with german content)

Relevant ffmpeg output
```
  Stream #0:6(eng): Subtitle: hdmv_pgs_subtitle
  Stream #0:7(eng): Subtitle: hdmv_pgs_subtitle (default)
  Stream #0:8(deu): Subtitle: hdmv_pgs_subtitle
  Stream #0:9(deu): Subtitle: hdmv_pgs_subtitle
  Stream #0:10(tur): Subtitle: hdmv_pgs_subtitle
  
Stream mapping:
  ...
  Stream #0:6 -> #0:6 (copy)
  Stream #0:7 -> #0:7 (copy)
  Stream #0:8 -> #0:8 (copy)
  Stream #0:9 -> #0:9 (copy)
  Stream #0:10 -> #0:10 (copy)
  ```
Relevant ffmpeg arguments:
```
-map 0:s:0 -c:s:2 copy -metadata:s:s:0 language=deu
-map 0:s:1 -c:s:3 copy -metadata:s:s:1 language=deu
-map 0:s:2 -c:s:0 copy -metadata:s:s:2 language=eng
-map 0:s:3 -c:s:1 copy -metadata:s:s:3 language=eng
-map 0:s:4 -c:s:4 copy -metadata:s:s:4 language=tur
```

**Comment by GamerBene19** [comment]
Reordering audio works as expected with the following outputs/arguments:
```
  Stream #0:1(deu): Audio: dts (DTS-HD MA) ([1] [0][0] / 0x2001), 48000 Hz, 5.1(side), s16p (default)
  Stream #0:2(deu): Audio: dts (DTS) ([1] [0][0] / 0x2001), 48000 Hz, 5.1(side), fltp, 1536 kb/s
  Stream #0:3(eng): Audio: dts (DTS-HD MA) ([1] [0][0] / 0x2001), 48000 Hz, 5.1(side), s32p (24 bit) (default)
  Stream #0:4(eng): Audio: dts (DTS) ([1] [0][0] / 0x2001), 48000 Hz, 5.1(side), fltp, 1536 kb/s
  Stream #0:5(tur): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), fltp, 448 kb/s

Stream mapping:
  ...
  Stream #0:3 -> #0:1 (copy)
  Stream #0:4 -> #0:2 (copy)
  Stream #0:1 -> #0:3 (copy)
  Stream #0:2 -> #0:4 (copy)
  Stream #0:5 -> #0:5 (copy)
```

```
-map 0:a:2 -c:a:0 copy -metadata:s:a:0 "title=Surround 5.1" -metadata:s:a:0 language=deu
-map 0:a:3 -c:a:1 copy -metadata:s:a:1 "title=Surround 5.1" -metadata:s:a:1 language=deu
-map 0:a:0 -c:a:2 copy -metadata:s:a:2 "title=Surround 5.1" -metadata:s:a:2 language=eng
-map 0:a:1 -c:a:3 copy -metadata:s:a:3 "title=Surround 5.1" -metadata:s:a:3 language=eng
-map 0:a:4 -c:a:4 copy -metadata:s:a:4 "title=Surround 5.1" -metadata:s:a:4 language=tur
```

I think the issue is that the language tags for the subtitles gets set wrong.
Compare  
`-map 0:a:2 -c:a:0 copy -metadata:s:a:0 "title=Surround 5.1" -metadata:s:a:0 language=deu`  
to  
`-map 0:s:2 -c:s:0 copy -metadata:s:s:2 language=eng`

**Comment by GamerBene19** [comment]
After a bit of investigation there are two things wrong here (afaict):
1. The metadata argument is associated with the wrong stream (this is not the actual problem - it just makes it harder to read the command)  
e.g. `-map 0:s:2 -c:s:0 copy -metadata:s:s:2 language=eng` should be `-map 0:s:2 -c:s:0 copy -metadata:s:s:0 language=deu`
2. The actual problem: The order of the `-map 0:s:2 -c:s:0 copy` arguments is wrong.
The order of the maps determines the order of the output streams. So you need to make sure that they are in the order they should be in (as with the audio streams)

In my example the proper order would be
```
-map 0:s:2 -c:s:0 copy -metadata:s:s:0 language=deu 
-map 0:s:3 -c:s:1 copy -metadata:s:s:1 language=deu 
-map 0:s:0 -c:s:2 copy -metadata:s:s:2 language=eng 
-map 0:s:1 -c:s:3 copy -metadata:s:s:3 language=eng 
-map 0:s:4 -c:s:4 copy -metadata:s:s:4 language=tur 
```
but as explained in 1., even with (only!) the metadata arguments in the wrong place it still works as expected (it is just way harder to understand):
```
-map 0:s:2 -c:s:0 copy -metadata:s:s:2 language=eng 
-map 0:s:3 -c:s:1 copy -metadata:s:s:3 language=eng 
-map 0:s:0 -c:s:2 copy -metadata:s:s:0 language=deu 
-map 0:s:1 -c:s:3 copy -metadata:s:s:1 language=deu 
-map 0:s:4 -c:s:4 copy -metadata:s:s:4 language=tur 
```

I think that this is just a small bug when ordering the arguments. The actual logic seems to be present (and correct) already as the reordering of audio tracks works as expected.

**Comment by revenz** [comment]
assuming this works now as not heard back

**Comment by GamerBene19** [comment]
I've only tested the file that I initially noticed the issue on. As mentioned in Discord it the new plugin version seems to have fixed this issue. I'll report back if I find a file where it still occurs (I don't think that there will be one)
