### ISSUE TITLE
[bug] Crop Detection does not work if video length is shorter than 60 seconds

### ISSUE THREAD

**Issue by tavalin** [revenz/FileFlows#169]
I'm trying to test my flow with a sample file that is 24 seconds.

The command FF uses is generated as:

`ffmpeg  -ss 60 -i "/downloads/complete/Series/Tests/input.mkv" -hide_banner -vframes 25 -vf cropdetect -f null -`

and results in 

`Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)`

but if I manually run the command using the duration of the file the command looks like:

`ffmpeg  -ss 24 -i "/downloads/complete/Series/Tests/input.mkv" -hide_banner -vframes 25 -vf cropdetect -f null -` and results in:

```
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:25 x2:3839 y1:300 y2:1885 w:3808 h:1584 x:30 y:302 pts:121 t:0.121000 crop=3808:1584:30:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:24 x2:3839 y1:300 y2:1885 w:3808 h:1584 x:28 y:302 pts:162 t:0.162000 crop=3808:1584:28:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:22 x2:3839 y1:299 y2:1885 w:3808 h:1584 x:28 y:302 pts:204 t:0.204000 crop=3808:1584:28:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:20 x2:3839 y1:299 y2:1885 w:3808 h:1584 x:26 y:302 pts:246 t:0.246000 crop=3808:1584:26:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:20 x2:3839 y1:299 y2:1885 w:3808 h:1584 x:26 y:302 pts:287 t:0.287000 crop=3808:1584:26:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:20 x2:3839 y1:299 y2:1885 w:3808 h:1584 x:26 y:302 pts:329 t:0.329000 crop=3808:1584:26:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:18 x2:3839 y1:299 y2:1885 w:3808 h:1584 x:26 y:302 pts:371 t:0.371000 crop=3808:1584:26:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:16 x2:3839 y1:299 y2:1885 w:3824 h:1584 x:16 y:302 pts:412 t:0.412000 crop=3824:1584:16:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:15 x2:3839 y1:299 y2:1885 w:3824 h:1584 x:16 y:302 pts:454 t:0.454000 crop=3824:1584:16:302
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:15 x2:3839 y1:298 y2:1885 w:3824 h:1584 x:16 y:300 pts:496 t:0.496000 crop=3824:1584:16:300
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:15 x2:3839 y1:298 y2:1885 w:3824 h:1584 x:16 y:300 pts:537 t:0.537000 crop=3824:1584:16:300
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:12 x2:3839 y1:298 y2:1885 w:3824 h:1584 x:14 y:300 pts:579 t:0.579000 crop=3824:1584:14:300
[Parsed_cropdetect_0 @ 0x55cf87c82a00] x1:10 x2:3839 y1:298 y2:1885 w:3824 h:1584 x:14 y:300 pts:621 t:0.621000 crop=3824:1584:14:300
```

Suggested fix would be to amend the code [here](https://github.com/revenz/FileFlowsPlugins/blob/ca8de953db124ba844209e0fc594d2c7f60b1715/VideoNodes/FfmpegBuilderNodes/Video/FfmpegBuilderCropBlackBars.cs#L62) to use the length of the video stream if under 60 seconds, else start at 60 seconds.

**Comment by revenz** [comment]
fixed.
anything under 2 seconds will be skipped.

under 10 seconds, it will detect at 1 second

under 360 seconds, it will divide the duration by 5 and check at increment, increment* 2, increment* 3, increment* 4   eg 10sec would be 2,4,6,8

anything over 360 seconds it uses the original 60, 120, 240, 360
