### ISSUE TITLE
[Request] Ability to force a file through multiple libraries

### ISSUE THREAD

**Issue by jarhed** [revenz/FileFlows#170]
We have several flows we would like the same file to go through. I.e:

1. File captured from media, saved in directory A
2. File is normalised from directory A, moved to directory B
3. File is taken from directory B, scanned for blue-screen and static. Frames removed and moved to directory C
4. File is taken from directory C, creates a directory based on its own name and moves itself into that directory

The problem we have at the moment is that once the file has been processed in one library, it doesn't seem to get taken up by another library

**Comment by revenz** [comment]
is there a reason you want to create so many temp files like this?   you could just use multiple flows and use "Goto" if you want to break it up like that.

**Comment by revenz** [comment]
closing as no update
