### ISSUE TITLE
Multi select with shift

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#177]
Using shift to select multiple lines does not  currently work for any tabled views within FileFlows

https://user-images.githubusercontent.com/4150588/177926984-d38cf2bb-a779-4ea1-be11-1fe32aca802b.mp4

**Comment by revenz** [comment]
added
shift to select mutliple.  requires the previous item selected, then new item selected with shift

shift + ctrl to unselect, same as other, just hold ctrl as well to unselect items.
