### ISSUE TITLE
Feature: Add refresh button to library view

### ISSUE THREAD

**Issue by luigi311** [revenz/FileFlows#18]
View refresh button to the library view so we dont have to click to a different tab and then back
Add refresh to the log view as well

A live update would be better so the user doesnt have to click anything and it doesnt clutter the display

**Comment by revenz** [comment]
if you mean Library Files, you can just click the same tab to do a refresh, you don't have to go to a different tab then come back.  

Live refresh, can cause issues if you are selecting multiple items and then it refreshes clearing your selection.  These are ways around this, however... Not sure if a live refresh is really need.  The dashboard provides the "live" view of upcoming/complete and currently processing, and you can do a manual refresh clicking the active tab.

**Comment by luigi311** [comment]
I was referring to these two screens, as of right now i have to click on 14 Unprocessed for it to refresh to see if the processing ones are done. For the log its similar where i have to close it out and enter unprocessed and then go back to processing. I would be fine with just the log view being live since that would be with only a single file right?
![image](https://user-images.githubusercontent.com/4695527/159662827-cba47636-396f-46cf-b9cb-0bdc5be46942.png)

![image](https://user-images.githubusercontent.com/4695527/159662922-738a3e48-3e0b-49d6-888c-5a2519f0d84b.png)

**Comment by revenz** [comment]
What browser?   If you just click the same tab it should refresh.  
![lf-refresh](https://user-images.githubusercontent.com/958400/159663743-791ecd43-69b9-45b9-95af-0606572a6fc1.gif)

Also the log should also auto refresh every few seconds.

This is working fine on Vivaldi

**Comment by luigi311** [comment]
ahhh didnt realize you can click on the processing and it will load it again. Ohh perfect didnt realize that the log auto updated every couple of seconds. Sounds like this isnt really an issue then lol. Ill go ahead and close it.
