### ISSUE TITLE
Library Template - filter overwritten

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#185]
It appears i've somehow managed to overwrite the standard template filter

If i create a new library, select "video generic", this is the filter that is applied,
\.(ts|mp4|mkv|avi|mpe|mpg|mov|mpv|flv|wmv|webm|avchd|h(\.)?26[45])$

My understanding is the default filter at install is this
\.(ts|mp4|mkv|avi|mpe|mpg|mov|mpv|flv|wmv|webm|avchd)

If this is indeed the case, i would suggest considering making sure all "templates" cannot be overwritten. This caused 30 minutes of confusion for me when i was setting up a new library and could not understand why files were missing.

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/178132769-ccb5ed0e-5914-4691-8071-b36668e3e6db.png)
 what you have is the default
