### ISSUE TITLE
Video Encode ignores video settings if same encode codec type

### ISSUE THREAD

**Issue by chaddm** [revenz/FileFlows#19]
First, thank you for making this software.  I have been looking for something like this for a long time.

# Issue

I have a File Flow accepts a file, transcodes it with particular set of encoding parameters (h265, rescaled, bitrate requirements), and moves the final file in an output directory.  If the input format is anything other than h265, it works as expected.  If the input format is already h265, the Video Encode parameters are ignored, the video parameters used are `-y -map 0:v -c:v copy -map 0:1`, and the video stream is copied, not re-encoded.

# Expectation

I expect the Video Encode parameters to be used regardless of the input file's video codec type.

# Reproduction

Using the following flow:

```json
{
  "Enabled": true,
  "Description": "A blank file template with a single \u0022Input File\u0022 input node.",
  "Template": "Blank File Template",
  "Parts": [
    {
      "Uid": "ae28a059-5189-40c6-870f-50464a46bfef",
      "Name": "Encode to DVDP",
      "FlowElementUid": "FileFlows.VideoNodes.VideoEncode",
      "xPos": 343,
      "yPos": 208,
      "Icon": "far fa-file-video",
      "Label": "",
      "Inputs": 1,
      "Outputs": 2,
      "OutputConnections": [
        {
          "Input": 1,
          "Output": 1,
          "InputNode": "befabab8-6891-4fed-b521-004f566eb8a5"
        }
      ],
      "Type": 2,
      "Model": {
        "VideoCodec": "h265",
        "VideoCodecParameters": "libx265 -preset slow -crf 24  -tag:v hvc1 -vf setdar=dar=dar,scale=720x480 -pix_fmt yuv420p -movflags faststart -profile:v main -level 6.2 ",
        "AudioCodec": "eac3 -b:a 384k ",
        "Language": "eng",
        "Extension": "mp4"
      }
    },
    {
      "Uid": "befabab8-6891-4fed-b521-004f566eb8a5",
      "Name": "Move to DVDP",
      "FlowElementUid": "FileFlows.BasicNodes.File.MoveFile",
      "xPos": 343,
      "yPos": 358,
      "Icon": "fas fa-file-export",
      "Label": "",
      "Inputs": 1,
      "Outputs": 1,
      "OutputConnections": null,
      "Type": 2,
      "Model": {
        "DestinationPath": "/media/media/new/DVDP",
        "DestinationFile": null,
        "MoveFolder": false,
        "DeleteOriginal": false,
        "AdditionalFiles": [],
        "AdditionalFilesFromOriginal": false
      }
    },
    {
      "Uid": "469883bf-eb77-4adc-9f84-201baddba0c6",
      "Name": "Input Video File",
      "FlowElementUid": "FileFlows.VideoNodes.VideoFile",
      "xPos": 343,
      "yPos": 63,
      "Icon": "fas fa-video",
      "Label": "",
      "Inputs": 0,
      "Outputs": 1,
      "OutputConnections": [
        {
          "Input": 1,
          "Output": 1,
          "InputNode": "ae28a059-5189-40c6-870f-50464a46bfef"
        }
      ],
      "Type": 0,
      "Model": {}
    }
  ],
  "Uid": "5ae5f30e-2e60-4571-98ab-bce5d5dd2703",
  "Name": "Test Video Convert",
  "DateCreated": "2022-03-27T11:38:02.636524-05:00",
  "DateModified": "2022-03-27T11:51:08.1060037-05:00"
}
```

Run the flow with a file already encoded to `h265`.

**Comment by revenz** [comment]
set the video codec to IGNOREME (anything really)
![image](https://user-images.githubusercontent.com/958400/160297508-c4e491d7-6848-4bf9-92a1-a74c2d4d1a04.png)

This parameter is used to check if the video needs reencoding, if it matches that codec it wont be reencoded (unless it has blackbars that need trimming).     By settings this to something that wont match, it will never say its the same codec and always reencode.

**Comment by chaddm** [comment]
From a technical point of view, I see how that works.  Thank you for the information.

From a user experience point of view, I would recommend updating the `Video Codec` to `Target Video Codec` and the text to something like `Encode video unless the input file's codec matches this name (ie "h264").  If left empty, all original video tracks will be copied.`.  This software is great way to set up a video pipeline, so I suspect other people will want to be able to do the same.  Alternatively, I think it might be more intuitive if there is an additional option under this one with something like `Always encode`, default to `false`, and with text of `If set to "on", the input video will be encoded even if it already is in the specified format.`.

Again, thank you for the speedy response and the project.

**Comment by revenz** [comment]
will do
