### ISSUE TITLE
Plex Analyze not working

### ISSUE THREAD

**Issue by aStonedPenguin** [revenz/FileFlows#203]
Plex Analyze is failing. Plex server is on Windows. Presumably because it uses backslashes instead of forward slashes?

Version: Latest Docker build

![img](https://cdn.discordapp.com/attachments/911564792521711657/997187971897892895/MagentaAiredaleterrier.png)
![img](https://cdn.discordapp.com/attachments/911564792521711657/997187971612692511/EuphoricNarwhale.png)

**Comment by revenz** [comment]
fixed
