### ISSUE TITLE
Giving a script the same name as a defualt script makes all scripts fail to load

### ISSUE THREAD

**Issue by aStonedPenguin** [revenz/FileFlows#208]
Duplicating a default script also does this.

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/179133007-2f16ded6-b03b-4ca3-96f5-cc271f756b4a.png)
you shouldnt be able to save a default script

**Comment by aStonedPenguin** [comment]
Ctrl S

**Comment by revenz** [comment]
see that information would be good to put in the description other than "see title" :P

**Comment by revenz** [comment]
go to the User script and delete the duplicate one.   I already have a ticket to fix the underlying issue
https://github.com/revenz/FileFlows/issues/197

didn't put into 0.9.0 due to it being low risk and could wait until 0.9.1.

**Comment by revenz** [comment]
fixed the ctrl-s.

the duplicate works as expected.  its just you create the issue with ctrl-s which #197 fixes causing scripts not to load, meaning you cannot duplicate.   

but if you fix the same named script from the user script folder, then duplicate a system script, it should create a "ScriptName (2)" in the user folder
