### ISSUE TITLE
[Bug] FF running in "demo" mode even though nodes configured and running

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#216]
I booted FileFlows for the first time, configured it and started using it. FileFlows was stuck in first-time-use mode preventing me from using dashboards. 

Restarting file-flows resolved the issue.

https://user-images.githubusercontent.com/4150588/179353173-2d9912ed-8b6d-4e07-8cbe-759a1715a44c.mp4

**Comment by revenz** [comment]
If this ever happens again a F5 should fix it.

It gets "config" from the e server when the app is first started (it first starts on a refresh aswell).   for some reason the is said flows wasn't configured.

or if you added a flow it would have fixed it aswell.

closing as a random thing.

**Comment by Sprooty** [comment]
As per attached video, i had a flow configured. Quite sure i also tried an F5 refresh which didn't trigger it to change.

**Comment by revenz** [comment]
i meant add another flow.  not sure if you hit f5, I'm 99% sure that would have fixed it, video deosn't show a refresh
