### ISSUE TITLE
[Request] Show file processing completion percentage per file on Files > Processing window

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#217]
Dashboard already has similar functionality; would be good to see it on processing tab

![SNAG-0003 17-07-2022 5 02 11 PM](https://user-images.githubusercontent.com/4150588/179387911-ddeaf86e-38d4-48f0-b323-624a4c1c0508.jpg)
![SNAG-0002 17-07-2022 5 02 05 PM](https://user-images.githubusercontent.com/4150588/179387913-b8aa3d19-df9f-4156-81c4-2cf035461bb5.jpg)

**Comment by revenz** [comment]
Depends on #54

**Comment by revenz** [comment]
done, this tab auto refreshes every 10 seconds.  

Blue == current progress
Pink == overall progress

![Image](https://github.com/revenz/FileFlows/assets/958400/a2234e51-3773-48da-8011-5b075a2a3ca2)
