### ISSUE TITLE
Suggestion: Specify which node may execute what flows

### ISSUE THREAD

**Issue by rickiewars** [revenz/FileFlows#218]
When configuring a node, it would be nice to specify which flows it may execute. (Flow whitelist/blacklist for each node)
It is already possible to filter on file-size but it would be nice to define multiple flows for different types of work and then specify that only certain nodes can (or can not) process files with them.

Optional: Asside from banning a node from a specific flow, it would be nice to specify prefered flows so that node will first process files with it's prefered flows and afterwards, only if no other node is available for the non-prefered flows, it will process them with those flows.

Using this feature, we can assign weaker nodes to lighter flows and the more powerfull nodes to the heavy flows.

**Comment by rickiewars** [comment]
One thing that can be an issue with this feature is that two nodes could execute different flows for the same file. 
This could be advoided by temporary locking the file for other nodes (if that has not already been inplemented somehow).

**Comment by revenz** [comment]
You can limit what libraries a node can execute.  Therefore you can achieve this that way.

Then the node will only get a file it can process.   So there's no issue there.

![image](https://user-images.githubusercontent.com/958400/179424627-06adf9c5-ffcb-4783-8dff-b2e712032807.png)

**Comment by rickiewars** [comment]
Oke, good to know.
I've one question left.
Is it possible to add the same library twice so I can assign two or more flows to the same directory?
This way I can assign for example:
- My weaker node to for example extract subtitles,
- My stronger node with GPU to modify the video files (encoding).

Would that be possible or will I then get issues as described in my previous post?

**Comment by revenz** [comment]
not possible.   you can include/exclude files from a library, so you could have the path in two libraries
eg /media
then have a Video library with filter *.mkv, and Image Library with filter *.png
which would be fine.   But if you use the same filter, whatever library finds that file first, is what will process that file.

if the only thing your weaker node can do is extract subtitle, just ditch that node altogether.  or put a file size limit on it so it only processes small files.
