### ISSUE TITLE
FFMPEG Builder: Subtitle Track Merge match filename should ignore .[lang]

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#228]
The FFMPEG Builder: Subtitle Track Merge node has an option to match filename.

If this is set it has to exactly match except the extension.  However some subtitles have a language code added to the the subtitle

eg 
- Movie.en.srt
- Movie [en].srt
- Movie-en.srt

Update the matcher to ignore these.

**Comment by revenz** [comment]
done

**Comment by toverux** [comment]
I've got a use case, my .lang.srt file is detected, but I also have .lang.forced.srt files, that are ignored.
Instead this node could match more aggressively, like "video.mkv" => extract "video" (strip extension) => match everything with name "video.*.srt".

Or could I use an Input File node with a pattern for that? But I don't know what token to use to match the current file name in the pattern.
