### ISSUE TITLE
Add Force option to Video Scaler Node

### ISSUE THREAD

**Issue by achurak** [revenz/FileFlows#23]
Would it be possible to add a "force" option to the video scaler node (disabled by default) for when the file's codec, resolution and container are already correct (match the ones specified in the node's settings)? It would be nice to be able to decide whether you want to still process the file or just skip the node and move on to the next one. Might also be a good idea to add a second output based on whether the file was processed or not (processed > go to the renamer node, skipped > do nothing for example).

Feel free to close if it makes no sense or implementation not worth the effort. Thanks!

**Comment by revenz** [comment]
fixed by https://github.com/revenz/FileFlows/issues/21
