### ISSUE TITLE
[Naming] Track Remover shows as Audio Track Remover in log

### ISSUE THREAD

**Issue by jbiancam1** [revenz/FileFlows#235]
The Track Remover node displays as Audio Track Remover in log regardless of what type it actually is.
![image](https://user-images.githubusercontent.com/102190214/180317776-aa7fc49a-1614-4b6f-bad0-f1d537f2dcf4.png)
![image](https://user-images.githubusercontent.com/102190214/180318094-597b38e3-097c-4ab0-b67d-974ae5b531db.png)

**Comment by revenz** [comment]
fixed
