### ISSUE TITLE
Sugestion: Allow the FileFlows Server/Node to be run as a specific user in Docker

### ISSUE THREAD

**Issue by rickiewars** [revenz/FileFlows#236]
At the moment it's not yet possible out of the box to run Fileflows as an user other than root.
I've made a temporary entrypoint script to enable me to get around this limitation.
Basically, my script does the following:
- It changes ownership of /app to <uid>:<gid>
- It adds user of <uid> and group of <uid>
- It executes `/app/docker-entrypoint.sh` as the created user.

I would propose the following to easily change the user running FileFlows by implementing the following in the entrypoint script:
- Check if the enviornment variables `PUID` and `PGID` have been set. If not, just run FileFlows normally as root.
- Optionally you may want to assume that `PGID=$PUID` if `PGID` is not set, just a suggestion.
- Add the new group: `groupadd -g $PGID fileflows`
- Add the new user: `useradd -u $PUID -g $PGID fileflows`
- Change the ownership of the /app directory to the new user: `chown -R fileflows:fileflows /app`
- Run FileFlows as the new user:
  - Node: `su -c "/dotnet/dotnet FileFlows.Node.dll --docker true" fileflows `
  - Server: `su -c "/dotnet/dotnet FileFlows.Server.dll --urls=http://*:5000 --docker" fileflows `

Make sure that the new user has read and execute access to the `/dotnet/dotnet` executable.
Don't give the user more rights than it needs to advoid security risks.

**Comment by revenz** [comment]
Heres an updated docker-entry.sh, you can test this by just replacing it in the container

```bash
#!/usr/bin/env bash

# set -e makes the script exit when a command fails.
set -e

mode=server

if [[ "$FFNODE" == 'true' || "$FFNODE" == '1' || "$1" = '--node' ]]; then

    # check if there is an upgrade to apply
    if test -f "/app/NodeUpdate/node-upgrade.sh"; then
        printf "Upgrade found\n"
        chmod +x /app/NodeUpdate/node-upgrade.sh
        cd /app/NodeUpdate
        printf "bash node-upgrade.sh docker\n"
        bash node-upgrade.sh docker
    fi

    mode=node
    
else

    # check if there is an upgrade to apply
    if test -f "/app/Update/server-upgrade.sh"; then
        printf "Upgrade found\n"
        chmod +x /app/Update/server-upgrade.sh
        cd /app/Update
        printf "bash server-upgrade.sh docker\n"
        bash server-upgrade.sh docker
    fi
fi

if [[ -z "${PUID}" ]]; then

    if [[ "$mode" == "node" ]]; then

        printf "Launching node as root\n"
        cd /app/Node
        exec /dotnet/dotnet FileFlows.Node.dll --docker true

    else

        printf "Launching server as root\n"
        cd /app/Server
        exec /dotnet/dotnet FileFlows.Server.dll --urls=http://*:5000 --docker

    fi

else 
    # running as PGID/PUID
    pgid=${PGID}
    if [[ -z "${PGID}" ]]; then
        pgid="${PUID}"
    fi

    user=fileflows

    if id "${PUID}" &>/dev/null; then
        printf "${PUID} user exists\n"
        user="$(id -u -n)"
    else
        if [ $(getent group $pgid) ]; then
            printf "group $pgid exists\n"
        else
            printf "fileflows group does not exist, creating\n"
            groupadd -g $pgid fileflows
        fi

        printf "user '$user' does not exist, creating\n"
        useradd -u "${PUID}" -g $pgid $user
        if id "${PUID}" &>/dev/null; then
            printf "created user '$user'\n"
        else
            printf "failed to create user '$user'\n"
            exit
        fi
    fi

    printf "changing owner of /app to: ${PUID}:$pgid\n"
    chown -R "${PUID}:$pgid" /app
    printf "changed owner of /app to: ${PUID}:$pgid\n"

    if [[ "$mode" == "node" ]]; then
        printf "Launching node as '$user'\n"
        cd /app/Node
        su -c "/dotnet/dotnet FileFlows.Node.dll --docker true" $user

    else
        printf "Launching server as '$user'\n"
        cd /app/Server
        su -c "/dotnet/dotnet FileFlows.Server.dll --urls=http://*:5000 --docker" $user
    fi
fi

```

Let me know how it goes, works on my system

**Comment by revenz** [comment]
fixed
