### ISSUE TITLE
[Bug] Movile File -  Execution error: Attempted to divide by zero

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#238]
Potential the file in question was corrupt, but would expect FF not to bomb out and to move the file anyway as that's what the Flow was designed to do.
[UpdatedTVFindandReplace(3).json.log](https://github.com/revenz/FileFlows/files/9165009/UpdatedTVFindandReplace.3.json.log)
[c59b1faa-8430-4fa3-b2cc-75723c184c5e.log](https://github.com/revenz/FileFlows/files/9165012/c59b1faa-8430-4fa3-b2cc-75723c184c5e.log)

**Comment by revenz** [comment]
fixed
