### ISSUE TITLE
audiobook combine and convert

### ISSUE THREAD

**Issue by binarygeek119** [revenz/FileFlows#253]
i would like to combine and convert audiobook files. 
formats 
mp3
flac/cue
wma
m4a/m4b
aac
wav

the best format is m4b (aac) a audiobook mp3 format.
info 
https://fileinfo.com/extension/m4b

a tool to take a look at 
https://github.com/yermak/AudioBookConverter

M4B is the gold standard as far as i know

**Comment by revenz** [comment]
when you say combine.  do you mean a book is split into multiple mp3 files for instance for each chapter?  then you want to combine them into a single m4b with the chapters correctly set?

**Comment by binarygeek119** [comment]
Yes all though I can deal with out chapters if to much. There's a audio book converter on steam you could look at.

**Comment by revenz** [comment]
just making this super clear, so what would the input be, and what would the output be?

If you were to use a folder library, then each folder had a book in it split into multiple mp3s eg
```
mybook/chaprter01.mp3
mybook/chaprter02.mp3
mybook/chaprter03.mp3
mybook/chaprter04.mp3
mybook/chaprter05.mp3
mybook/chaprter06.mp3
```
then fileflows would process the "mybook" folder, the flow would have a node called something like "Combine into m4b"  which would look at all audio files it could handle (in this case mp3s), then just join those all together using ffmpeg and setting chapter points to where each chapter file was joined.

so output would finally be
```
outputdir/mybook.m4b
```

My main question is, what does the input look like?   if its not in separate folders, then how are they stored?   you could then use a audio file input with a file library, and the file library could only look for chapter[0]*1\.(mp3|aac|whatever)$ so it only added the first chapter into fileflows for processing (you wouldnt want FF to process each chapter, that would cause problems). 

so... how are they stored?

**Comment by binarygeek119** [comment]
types of audiobook
![image](https://user-images.githubusercontent.com/72405030/200198599-702c6e53-3421-4b95-8335-cbb60ac673dd.png)

![image](https://user-images.githubusercontent.com/72405030/200198675-3298877c-54ed-4921-b492-991da83c3c11.png)

![image](https://user-images.githubusercontent.com/72405030/200198711-919ddcce-a5e7-4d77-8f93-ee0ed2f8eb74.png)

![image](https://user-images.githubusercontent.com/72405030/200198719-75a2a15b-d505-47cc-866b-a77c45660c6c.png)

![image](https://user-images.githubusercontent.com/72405030/200198744-919d8764-3c79-4ae2-b7ed-f2687291702b.png)

the joined mp3's will be the start chapters in the new m4b file

**Comment by revenz** [comment]
Uploaded to the preview plugins (in 1.0.6.451 and above)

![image](https://user-images.githubusercontent.com/958400/202886501-06451116-f292-46e4-9b5a-3b1ab0dab954.png)

It converts the audio to aac (copying would fail in ffmpeg) into a m4b container.  It will create chapter points (these can be a few seconds off, but close enough).  

It requires to be run against a folder, so library type folder, "Input Folder", it will then scan for mp3s etc in that directory (not recursive) and create a m4b if more than one audio tracks are found.

Tested against the audio book samples you provided.
