### ISSUE TITLE
comic converters

### ISSUE THREAD

**Issue by binarygeek119** [revenz/FileFlows#254]
i would like to be able to convert comic books 

pics in a zip like archive 
RAR 
ZIP 
7Z
GZ
BZ2

CBR - https://fileinfo.com/extension/cbr
CBZ - https://fileinfo.com/extension/cbz
CB7 - https://fileinfo.com/extension/cb7
PDF
EPUB

CBZ is the gold standard as far as i know 

tool to look at 
https://github.com/gen2brain/cbconvert

**Comment by revenz** [comment]
added to v1.0.0

can convert to: cbz, pdf 

can convert from: cbr, cb7, cbz, pdf, gz, bz2, zip

Skipping epub for now, a lot more complex.

Cannot add support to compress to cbr as that is a properitery format.   

Skipping the creation of cb7 for now as well, as that is not a commonly used format, and likely just want to convert from it.

Pages are extracted and renamed if necessary, eg page1, page2... page11, become page01, page02, page11.  To avoid any file sorting issues (some sample comics from the internet archive had files named this way).
