### ISSUE TITLE
Suggestion: Rename "Delete" option to "Forget"/"Delete From History" in Files section

### ISSUE THREAD

**Issue by DareFox** [revenz/FileFlows#264]
It's kinda counter-intuitive. I thought `Delete` button in Files tab means delete file and it's history entry in FIleFlows. 

I spend an hour to discover that it only deletes history entry, not files. This situation was awkward, and to prevent situations like these for other people, I think button name should have more meaning. Like `Forget` or `Delete From History`

**Comment by revenz** [comment]
renamed button for files to "Remove" and update the confirmation message



![Image](https://user-images.githubusercontent.com/958400/183235917-328d86c6-a65b-46da-a1d6-a5cebc00f584.png)
