### ISSUE TITLE
Completed jobs are left in the processing tab

### ISSUE THREAD

**Issue by brianharwell** [revenz/FileFlows#288]
I have a pretty basic flow...

![image](https://user-images.githubusercontent.com/1017867/185169966-48504476-0940-44da-a773-ba75f0ca7319.png)

The info on the file shows that it's still processing...

![image](https://user-images.githubusercontent.com/1017867/185170586-e9683049-ecf6-4e27-9a0e-2a2f6a2562c3.png)

But the log for the file shows that it has finished processing...

![image](https://user-images.githubusercontent.com/1017867/185170906-1d8d10ae-cd74-429b-a7e8-fd89d9697dac.png)

**Comment by revenz** [comment]
What version?  is this still happening on 1.0.2.1951?

**Comment by brianharwell** [comment]
No, you fixed this
