### ISSUE TITLE
Windows out of schedule files not appearing correctly

### ISSUE THREAD

**Issue by AndrewMcAwesome** [revenz/FileFlows#292]
when a library is out of schedule, it's file count is adding to the disabled category, instead of out of schedule, but the file names don't appear in the list
Version: 1.0.1.1924 using mysql

![image](https://user-images.githubusercontent.com/94072672/186212566-df4d0aaa-f5cd-4cbc-a681-36480ccdc25e.png)

**Comment by revenz** [comment]
fixed by #296
