### ISSUE TITLE
FR : Add Storage Saved directly in the graph instead of only on over

### ISSUE THREAD

**Issue by hbooo** [revenz/FileFlows#293]
Given flows already have lead to saved some space
When I reach home page and check Storage Saved widget
Then I would like to be able to see saved space without having to over the graph 

![image](https://user-images.githubusercontent.com/242125/186666045-9d33da5b-ade2-4fc4-83d3-5905dd656e29.png)

**Comment by revenz** [comment]
added to the premium dashboard



![Image](https://user-images.githubusercontent.com/958400/188057879-c7ee0c13-866d-467c-8db4-7137073a6357.png)
