### ISSUE TITLE
Variable execution is imperfect

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#301]
run this code
```Variables.file.Name.match(/test/)```
it will fail saying match is not a known fucntion.

This is because the code executor is converting it to 
```Variables["file.Name"].match(/test/)```
And Variables is a object dictionary, so Variables["file.Name"] is of type object not string.

Work around is to use
```Variables.file.Name.toString().match(/test/)```
but this is not user friendly

Need to fix this and not break the ability to set variables.

**Comment by revenz** [comment]
this is a limitation of the code execution, not an elegant solution around it.  

for the time being, I've put in place a auto conversion for variables starting with folder./file. as these should be treated as read only variables.

so 
```Variables.file.Name.match(/test/)```
will work now

**Comment by brianharwell** [comment]
Thanks!

**Comment by brianharwell** [comment]
I was able to add a function to a flow with `Variables.file.Name.match(/\b2160p\b/g);`
