### ISSUE TITLE
SMB/Mapped Drive support on Windows?

### ISSUE THREAD

**Issue by banjoboy96** [revenz/FileFlows#305]
I installed Fileflows on one server and one node (both Windows 10) yesterday and have been doing some learning and exploring, however I'm struggling with adding my desired library. Currently both the server and the node can access my NAS - which has all my media content on it - via SMB, mapped as the Z: drive on both.

When I came to add the library in the Web GUI I can't see the Z: drive listed, and if I write out the UNC path manually e.g. "\\[NAS IP address]\Storage\Conversions" then whenever FileFlows tries to scan the library it comes back with a "Library 'Test' path not found" error.

Am I missing something or is FileFlows unable to see/use mapped network drives, and if that's the case would there be any chance of them being supported in the future? I'm sure with some juggling around I can make it work otherwise, but it'd be great to keep my current setup and have everything work.

Thanks in advance! :)

**Comment by revenz** [comment]
just add the library/path as you normally would for smb.

\\server\folder

**Comment by banjoboy96** [comment]
Got to say I feel a bit stupid about this one - I had run FileFlows as an admin which meant it didn't have access to the share which is mapped under my standard user account... a classic case of user error! Thanks for your help :)
