### ISSUE TITLE
FFMPEG Builder: Bitrate being ignored

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#307]
on videos bitrate is set, but ignored
``` -b:v:0 10000k -minrate 7500k -maxrate 12500k```

**Comment by AhDoozy** [comment]
Any update on this? I'm waiting on this fix to do some more tests. :)

**Comment by revenz** [comment]
needs more testing, another user just reported hardware encoding not working when bitrate was set but video encode didnt flag a change as needed.

Which means bitrate isn't being ignored.  I suspect it might be if the target bitrate is above the source bitrate it maybe ignored.

**Comment by revenz** [comment]
https://trac.ffmpeg.org/wiki/Encode/H.264

not a bug.  this is how FFmpeg works.

If using CRF, whcih the Video Encode node uses, bitrate will not be used, it cannot be used.

So if a user wants to use bitrate, they cannot use Video Encode node.  They can use Video Codec node and use the parameters
 "h265" or "hevc" to use nvidia/qsv/amf/vaapi if available, falling back to cpu if not.  or "h264" to use the same but with h264.
