### ISSUE TITLE
File are not listed by date processed

### ISSUE THREAD

**Issue by brianharwell** [revenz/FileFlows#309]
#### What's it doing?
As seen in the screenshot, the files are sorted in an unknown order.

#### What should it do?
The files should be sorted in order from most recent.

Version: 1.0.2.1951

![188317497-8fc9cbbe-b7a9-48b7-ab71-e7192425ed4f](https://user-images.githubusercontent.com/1017867/188318465-e676f64e-5fb2-497c-a7fc-76242c8f0704.jpg)

**Comment by revenz** [comment]
can you provide me your database for this? 

If using mysql/mariadb you can change back to sqlite for it to create a new sqlite db, then provide  that (assuming it also shows the error).

**Comment by brianharwell** [comment]
No sorry, I’m not going to send you my entire database.

What is the query that runs to populate the table? I can run that against the database and see if the files are listed in the proper order.



Sent from myMail for iOS


Sunday, September 4, 2022, 5:00 PM -0400 from Timofey Biryukov  ***@***.***>:

**Comment by revenz** [comment]
it prints the query to the log in 1.0.2.  just look there.

**Comment by revenz** [comment]
believe i have a fix for this, it orders the files by datemodified, which is generally when the file was last updated, which should be the correct date for processed.  but clearly not.

so for Processed status I'm ordering by ProcessingEnded now

**Comment by brianharwell** [comment]
Great idea!

Monday, September 5, 2022, 1:40 AM -0400 from Timofey Biryukov  ***@***.***>:

**Comment by brianharwell** [comment]
Tested and looks good!
