### ISSUE TITLE
Unable to set base URL for reverse proxy

### ISSUE THREAD

**Issue by samAnnisBrown** [revenz/FileFlows#31]
There doesn’t appear to be a config item to set a base URL path to allow FileFlows to be easily put behind a reverse proxy.  This is perhaps more a feature request than issue, or is this functionality that exists that I’ve missed?

To be clear, the ask is have a configurable base URL so all FileFlows requests can be modified from the standard:

http://fileflows.host/

to

http://fileflows.host/base/

Where ‘base’ is a config item available to users.

As it currently stands, I’d have to use a subdomain which is more complex in many configurations.

Thanks!  Awesome project by the way.  Love the UI and simplicity compared to others in this space :)

**Comment by revenz** [comment]
this is how i use it,  works fine.

![image](https://user-images.githubusercontent.com/958400/163501424-96075fca-96c4-411a-b208-4d7f83db7a9c.png)

Like any other app that is behind nginxproxymanager.

**Comment by samAnnisBrown** [comment]
Hi John,

Thanks for the quick response.

Yep, FileFlows will of course work behind a reverse proxy, but this assumes it’s the sole service behind a domain.  A common use case to expose a single domain externally (i.e. mydomain.com) then expose several services behind that domain.  I for instance have over a dozen services behind my domain.  Each service will have a base URL (i.e. service1, service2, etc) which is configured in each service.  This allows you to access said service via example.com/service1 for instance, or a separate service via example.com/service2.

With base url set, the service in question will automatically add the base (i.e. service1/) to all of it’s internal links, simplifying service sharing on a single domain.

Perhaps I’m missing something, but that doesn’t appear to be what you’re showing?  Simply that you can reverse proxy, which of course you can.

Sharing under a single domain is preferred however for DNS, SSL, and auth simplicity, since it can all be controlled at a single entry point.

Hope that makes sense, and please let me know if I’m still misunderstanding and there is a way to do this without complex URL rewrites in nginx.

**Comment by revenz** [comment]
can't you just use a subdomain per service?   that's what I do on anything I publicly expose.

**Comment by samAnnisBrown** [comment]
I guess the challenge is coming though something like Organizr, which is also the central auth solution.  The root domain passes through central auth, with base urls then passing onto each service.

A subdomain will bypass that root domain auth and becomes more complex to manage.

I had already considered a subdomain - it might be doable, even if more complex.  Let me deep dive on it more.
