### ISSUE TITLE
File sizes are not reported correctly

### ISSUE THREAD

**Issue by brianharwell** [revenz/FileFlows#311]
#### What's it doing?
I am seeing runs where the file size is not reported correctly but the logs show the correct size.

#### What should it do?
The file size should be reported properly in the Processed Tab and in the summary screen.

The Processed Tab is showing a 2.54GB increase in the size of the file
![Screenshot 2022-09-04 101103](https://user-images.githubusercontent.com/1017867/188318112-cb933f3b-89b9-4a73-898f-976ddea34fe5.jpeg)

The Info tab shows the same thing
![Screenshot 2022-09-04 101125](https://user-images.githubusercontent.com/1017867/188318191-1caa56f8-78bb-46bc-9c8a-a3398f1196c7.jpeg)

Here is the log file
[dc6a6273-c02a-486c-995d-aabf61d22f89.log](https://github.com/revenz/FileFlows/files/9484854/dc6a6273-c02a-486c-995d-aabf61d22f89.log)

The log file has these lines
```
Initial Size: 4456515502
Original Size: 4456515502
Final Size: 4456515502
```

Version: 1.0.2.1951

**Comment by revenz** [comment]
this may be fixed in next build, leaving open for confirmation

**Comment by brianharwell** [comment]
Still present in Version: 1.0.3.1967

![image](https://user-images.githubusercontent.com/1017867/189144974-0eda959b-a10b-4e85-9569-01418939a9a6.png)

```
2022-09-08 10:11:47.052 [INFO] -> Final Fingerprint: 23a16c18a5d822f39ad0007f06c78ad52762e77ea3002985eb4da6f2cbadc387
2022-09-08 10:11:47.053 [INFO] -> Original Size: 4696723826
2022-09-08 10:11:47.054 [INFO] -> Final Size: 4696723826
```

**Comment by revenz** [comment]
fixed
