### ISSUE TITLE
Feature Request:  FFmpeg Subtitle Track Merge to delete merged subtitle files.

### ISSUE THREAD

**Issue by systemmonkey42** [revenz/FileFlows#328]
Please add an option to the "Subtitle Track Merge" node to delete the merged subtitles after successful ffmpeg.

**Comment by revenz** [comment]
![Image](https://user-images.githubusercontent.com/958400/192080257-9003e747-3040-424b-b143-b7c29fd6a4a7.png)

new option in the next version.   only deletes if ffmpeg builder executor output is 1 (ran and created a file successfully)
