### ISSUE TITLE
Track Reorder - Default Track Flag

### ISSUE THREAD

**Issue by rrhymers** [revenz/FileFlows#339]
When utilizing Track Reorder to reorder audio tracks, I am seeing a behavior where the original audio track that was track 1 has the default track flag set as true while being set to track 2 after being processed by the Track Reorder node in addition to the newly-assigned track 1 having the default track flag set as true. For example: 

Pre-Processing: 
Audio#1: TrueHD Atmos (Default)
Audio#2: AC-3

Post-Processing: 
Audio#1: AC-3 (Default)
Audio#2: TrueHD Atmos (Default)

If possible, can the Track Reorder node strip the default track flag from all audio tracks, and then set the default track flag to true for the track being set as audio track 1?

**Comment by revenz** [comment]
fixed
