### ISSUE TITLE
Add a way to Limit CPU use

### ISSUE THREAD

**Issue by jameslmoss** [revenz/FileFlows#34]
My unraid server is using an intel quad core cpu, and I pin two cores 1 thread each to fileflows, it pegs any pinned cores out at 100% for most heavy tasks like folder/library processing and encoding via cpu is obviously going to be intensive.

A way to be able to say use .75% max of total/pinned cores would be great leaving some headroom on those cores for other smaller tasks.

Example from how unmanic approaches it: 
In the "Extra Parameters" field, add "--cpus='.5'".
"This example limits the container to 50% of a single core.         
If you have 2 cores available to this container, "--cpus='.5'" will equal 25% of that available CPU resources.        
To limit the CPU cores available to the continer, use "CPU Pinning"

Thanks and keep up the good work, love the visual approach makes this so much nicer interact with.

**Comment by revenz** [comment]
Quick google bought me to this
https://kuberty.io/blog/how-to-set-docker-memory-and-cpu/

Have you tried setting ExtraParameters in unraid?   

This seems like it would be best left up to the host, eg windows or in this case Docker.

**Comment by jameslmoss** [comment]
Thanks, no i did not think to try using the values from unmanic in the extra params here..
Am newish to all this, did not occur to me those may be related to docker and not app specific.
It looks like they work fine same tho
I've played around using 3 cores pinned, in extraparameters i added: --cpus='1.75' 
Those three cores now sit around 63-75% instead of 100%
That's great thank you.

Maybe add to wiki as a general note somewhere for noobs like me haha

**Comment by revenz** [comment]
Nice.  Wasn't sure if it would work either, glad it did.
