### ISSUE TITLE
Mapped paths between windows/linux have a mixture of forwards and backwards slashes.

### ISSUE THREAD

**Issue by systemmonkey42** [revenz/FileFlows#345]
With my Server on linux, and a Node on windows, all server paths have unix paths (forward slashes) while all filenames have their forward slashes converted to backward slashes when mapped to windows.

Unfortunately these backward slashes are not converted back to forward slashes when mapping back to Linux, resuting in the database field `OutputPath` (which is used to prevent automatically picking up output files and re-encoding them) never matches during a server scan

Eg, Original file
/media/plex/tv/show/episode.mp4

mapped file
\\server\share\tv\show\episode.mp4

converted file
\\server\share\tv\show\episode.mkv

unmapped file
/media/plex\tv\show\episide.mkv

The database record in LibraryFile contains
name = `/media/plex/tv/show/episode.mp4` and
outputpath = `/media/plex\tv\show\episide.mkv`

During a subsequence disk check, the new file

`/media/plex/tv/show/episode.mkv` doesn't match either of the original or output filenames, and is
re-processed.

**Comment by revenz** [comment]
fixed
