### ISSUE TITLE
Add option to preserve original file (modification) time

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#346]
It would be cool if the copy/move file/folder nodes would have an option to preserve file modification times.
Usecase: I have some TV-Recordings where I only want to reorder some audio tracks and where it'd be nice to preserve the recording date.

**Comment by revenz** [comment]
done in next version, added "Preserve Dates" to copy/move/replace original nodes.

Note linux does not support changing the creation date, only the last write time
