### ISSUE TITLE
Investigation: Failed flows on external processing nodes results in empty log

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#35]
Reported in the field that when an external processing node flow fails, the library file log is shown as empty.

Need to investigate to see why this is happening and fix it if needed.

**Comment by GamerBene19** [comment]
I just tried out what happens to my logfile. It gets created in `/app/Logs/LibraryFiles` and stays there after completion. So it appears as if the logfile would be created as expected.

**Comment by revenz** [comment]
So the log file stil exists there afterwards, just for some reason its not being displayed?

**Comment by GamerBene19** [comment]
Looks like it yeah.

**Comment by GamerBene19** [comment]
Another info: The flow now was successful (it failed before) - now I can see log after completion.

**Comment by revenz** [comment]
thanks.  hopefully, I can reproduce it.

**Comment by revenz** [comment]
Unable to reproduce this, can you attach your full log of a library file that shows nothing?  Perhaps its something in the log causing it to fail (thinking when it creates an HTML version of the log)

**Comment by GamerBene19** [comment]
> Unable to reproduce this, can you attach your full log of a library file that shows nothing? Perhaps its something in the log causing it to fail (thinking when it creates an HTML version of the log)

See my update in #36.

**Comment by revenz** [comment]
If you open up the network tab, and see a call to "log" does that return anything in that?

I just had another issue when implementing the new "Mapping Issue" state where the log was there, but since that state was not in the approved list to show the log it would not be shown.  

What status is the file set to?
![image](https://user-images.githubusercontent.com/958400/165002605-27d10520-c879-40de-9930-4e28f1e9c35a.png)

**Comment by GamerBene19** [comment]
So I just tried to replicate this issue (have updated FileFlows in the meantime). And I was not able to replicate it. I think this issue can be closed.
