### ISSUE TITLE
Show the time according to the user's time zone

### ISSUE THREAD

**Issue by DareFox** [revenz/FileFlows#350]
Currently, web client doesn't care about time zone and shows all in UTC+0. 

In this example, on my machine the time zone is UTC+3, but the web version shows all the relative time ("X ago") in UTC+0 and because of that 3 phantom passed hours are added, although it just happened 

![image](https://user-images.githubusercontent.com/47672780/194784617-b6a5c5fc-47e1-460d-90dc-45a9f324363a.png)

**Comment by systemmonkey42** [comment]
This is the same issue which prompted #349, and should be resolved there.

**Comment by DareFox** [comment]
Duplicate
