### ISSUE TITLE
Show number of items processed successfully per library

### ISSUE THREAD

**Issue by boardyuk** [revenz/FileFlows#351]
I may be missing it but it would be great to be able to see the number of items processed successfully per library in the UI.

Use case would be seeing the status of processed files in a library of 1000 files, so if the UI showed 523 processed successfully then I'd know how many more were left to process for that library.

**Comment by revenz** [comment]
yup, I'll look into doing the same with the tooltip

**Comment by revenz** [comment]
![Image](https://user-images.githubusercontent.com/958400/198534316-4f900cbf-fcd4-4cc1-95e6-134a3f1c5649.png)

next version
