### ISSUE TITLE
Error with logs

### ISSUE THREAD

**Issue by snwaine** [revenz/FileFlows#352]
When trying to look at logs i get this error. im running FileFlow Version: [1.0.5.2071]
https://ibb.co/850S63D

**Comment by revenz** [comment]
what are you running FileFlows server on?  docker? windows? linux? mac?

can you open that file manually and see if there anything in that actual log aswell?

**Comment by snwaine** [comment]
I'm running it in docker and if i go to information on the left and click logs nothing in there and if i change the drop down on the right that is what throws the error but if i click download on any of the log options it downloads fine and the logs are full.

**Comment by revenz** [comment]
is this still an issue with 1.0.8?  I still haven't been able to reproduce this.

**Comment by revenz** [comment]
I was able to reproduce this, my adblocker was blocking the request, so try disabling adblockers on the fileflows site. 

My network tab showed "Blocked by AdBlocker Ultimate"

![Image](https://user-images.githubusercontent.com/958400/215364476-df15530c-fbb4-4627-a8e2-a6b6974b04d4.png)
