### ISSUE TITLE
[Feature Request] Add filters to variables

### ISSUE THREAD

**Issue by Scootter23** [revenz/FileFlows#354]
This came from my question if the variables file.Orig.Size and file.Size could have their numbers formatted to something more human readable. From the variable file.Orig.Size of 17278968927 to something like 17.2GB.

```
reven: I do like the idea of filters. Variable then |filter.
Eg {file.Orig.Size|number}
```

**Comment by revenz** [comment]
Added to the next version, see https://docs.fileflows.com/guides/variables (bottom of page)


![Image](https://user-images.githubusercontent.com/958400/198746857-2f4e11bc-d9f3-4ce0-852f-f27e28ca7060.png)
