### ISSUE TITLE
Fingerprint can be empty and cause duplicates

### ISSUE THREAD

**Issue by brianharwell** [revenz/FileFlows#355]
As my processed files has grown, I am seeing duplicates for files that are not close to being duplicates.

I was looking at https://github.com/revenz/FileFlows/blob/bb9a1a55cbb0f75f44a4678e257efbcc8170ea3d/ServerShared/Helpers/FileHelper.cs#L29 and I am thinking maybe a different algorithm should be used.

**Comment by revenz** [comment]
without any more information, I can't do much with this.

**Comment by brianharwell** [comment]
What additional information would you like?

**Comment by revenz** [comment]
reproduction steps would be nice.

obviously I havent seen this with my setup of 7500 files.   so this ticket isnt giving me anything to go on

**Comment by revenz** [comment]
fixed
