### ISSUE TITLE
"Could not find a part of the path" error (potential issue with long paths?)

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#36]
While copying the output of one of my flow runs I do get a "Could not find a part of the path" error?

I think it has to do something with the path beeing to long (at least thats what a quick google search told me). 
Additionally the same flow with a different file (with a  shorter path) on the same node, but with  did work as expected.

I will try to do some debugging to see if the pathname is indeed the problem and post further updates here

**Comment by GamerBene19** [comment]
Update: Just the same file but mounted at a different location worked this time.

**Comment by revenz** [comment]
What platform/system?  Is it on the internal processing node or external node?  If external what platform system is that?

Can you post the log?

Can you also post the exported Flow?

**Comment by GamerBene19** [comment]
Sorry for the late reply. It took me a (really) long time to reproduce the problem. Here is my update:

> What platform/system?

Sever: Ubuntu 22.04, External Node: Arch

> Is it on the internal processing node or external node?

The external node. While debugging I also tested some long path names on the internal node (such as `/output/_/the/path/to/this/folder/is/120/characters/long/_/here/are/some/more/folders/required/to/reach/the/length/end/`) they did _not_ fail (I did expect them to fail though if it were because of the long path name)

Steps to reproduce:
1. Make sure no nodes are enabled
2. On FileFlows server: `mkdir -p "/media/videos/Some Sample Folder (2022)/extras/" && cd "/media/videos/Some Sample Folder (2022)/"`
3. Download `sample_1280x720.mpeg` from [here](https://filesamples.com/formats/mpeg): `wget https://filesamples.com/samples/video/mpeg/sample_1280x720.mpeg -O "Failing Sample File__t01.mpe"`
4. Create output directory: `mkdir /output`
5. Recreate structure from 2 and 3 on external node aswell (I simply did it in my download folder)
6. Create mapping on external node for structure from step 5
`/media/videos/` => `/home/benedikt/Downloads`
8. Mount NFS-Share with `gvfs` (NFS-Share location is `192.168.10.27/media` in my case)
    > Mounting with `gvfs` results in the path  
`/run/user/1000/gvfs/nfs:host=192.168.10.27,prefix=%2Fmedia` for me
9. Ensure `output` directory is present on NFS-Share
10. Create mapping for output directory  
`/output` => `/run/user/1000/gvfs/nfs:host=192.168.10.27,prefix=%2Fmedia/output`
12. Import [bug flow](https://pastebin.com/0qpEgQYz)
13. Create new Video Library with input path as `/media/videos` and assign flow from previous step
14. Wait for "Failing Sample File__t01.mpe" file to be shown as unprocessed
15. Enable external node
16. Wait for processing to finish (should be successful)
17. Disable external node
18. Move sample file to `extras` directory (out of `extras`) on server and client node: `mv "Failing Sample File__t01.mpe" extras/`
19. Wait for moved file to be detected
20. Enable external node again
21. Wait for processing to finish (does fail this time) 
     > Note: You have to view log with shell on server, as it is not present in GUI as per #35)

> Can you post the log?

[Successful run](https://pastebin.com/MzX8kUSG) and [Failed run](https://pastebin.com/Rz9c28x9)

> Can you also post the exported Flow?

See step 12

**Comment by revenz** [comment]
That mapping looks very odd...
/output => /run/user/1000/gvfs/nfs:host=192.168.10.27,prefix=%2Fmedia/output

Could you map it locally to something more sane, like /mnt/output and have the OS do that crazy mapping?

**Comment by GamerBene19** [comment]
> That mapping looks very odd... /output => /run/user/1000/gvfs/nfs:host=192.168.10.27,prefix=%2Fmedia/output
> 
> Could you map it locally to something more sane, like /mnt/output and have the OS do that crazy mapping?

That mounting location is actually pretty normal when you mount with `gvfs` (e.g. if you mount your NAS from the file-browser in Ubuntu).
If I mount the NAS with normal `mount` (instead of `gvfs`) everything works fine (except it requires `root` permissions to mount). 
This also is the solution I settled for and which works. However this does require additional setup (compared to simply mounting with `gvfs`), because you have to create the folders for mounting first.

I could try to symlink the more sane location to the `gvfs` mountpath and see if it works. But I suspect it will as it will appear the same to FileFlows as my current solution.

**Comment by revenz** [comment]
closing this for now since you have a work around and this seems like an edge case.   if this one becomes a larger problem and affects more users I'll reinvestigate it.

**Comment by GamerBene19** [comment]
Yeah makes sense to close this. I don't think it will be a huge issue.  
Additionally mounting with `mount` instead of `gvfs` appeared to be more performant too.
