### ISSUE TITLE
An error occurred trying to start process 'xdg-open'

### ISSUE THREAD

**Issue by r4b8iiiiiit** [revenz/FileFlows#362]
When trying to run on an M1 Mac, getting this error: "An error occurred trying to start process 'xdg-open' with working directory '/Users/user/Downloads/FileFlows-1/Server'. No such file or directory"

**Comment by revenz** [comment]
does that directory exist?

**Comment by r4b8iiiiiit** [comment]
> does that directory exist?

It does yes

**Comment by revenz** [comment]
what is the exact command you are using to run it?

Sorry I haven't used a mac in years and dont have access to one.

**Comment by r4b8iiiiiit** [comment]
> what is the exact command you are using to run it?
dotnet FileFlows.Server.dll  - this is run from the Server directory as specified in the documentation

**Comment by r4b8iiiiiit** [comment]
> what is the exact command you are using to run it?
> 
> Sorry I haven't used a mac in years and dont have access to one.

dotnet FileFlows.Server.dll  - this is run from the Server directory as specified in the documentation

**Comment by revenz** [comment]
try
```
dontnet FileFlows.Server.dll --no-gui
```

**Comment by r4b8iiiiiit** [comment]
So that got me a step further, looks like it was crashing due to port 5000 already being in use. Looked up what on MacOS used port 5000 and turns out it is Airplay receiver. Disabled that and is working now! Thanks for your help 😊
