### ISSUE TITLE
Files: Duplicate

### ISSUE THREAD

**Issue by snwaine** [revenz/FileFlows#366]
Every file processed if renamed reports as duplicated after but there is actually only one file.
![XeMcH3o](https://user-images.githubusercontent.com/115901045/202426611-95438ce1-8959-4e83-ab41-ff6d8c50c89e.jpeg)

**Comment by ray73864** [comment]
I'm getting duplicates but not with same files.

My duplicates are with completely different files.

![2022-11-23 15_00_42-FileFlows and 9 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/1343103/203488572-495eddf7-ba50-4c89-a57d-89459285c464.png)

Every once in a while I go through and tell it to re-process those files, otherwise they just build up.

When I first discovered the issue, I had over 50 files sitting in there, not processed because it believed they were duplicates.

Once I tell FileFlows to re-process them, everything works out fine  until the next time it decides there are non-existent duplicates.

**Comment by revenz** [comment]
[snwaine](https://github.com/snwaine) can you send me your sqlite db file? just jump on discord and PM it.   
I want to see what the original file looks like in the db verses the duplicate.   

The code does currently check if a file exists with the exact same path or the path as the output path, so it should be excluding them.   So something else is going on.

**Comment by cereal-ninja** [comment]
Hi @revenz  did you ever get the sqlite DB file? I have the same issue. I checked SQLlite DB & seems like the output file path is loosing a forward slash at the end of the flow (shows in the log the same way). Am running FF Server on Docker on Linux & Node is running Windows 10 with Z drive mapped to SMB share.  Log & flow are attached.

![2022-12-03_18h43_26](https://user-images.githubusercontent.com/100738305/205467527-00886db3-60d7-44c5-af2b-9c977885d4e0.png)

![2022-12-03_18h45_08](https://user-images.githubusercontent.com/100738305/205467530-06ac68b0-c5d8-49ef-9465-13aa18acb741.png)

[e863dde3-6ab3-4bca-9462-b4b5fcb7e959.log](https://github.com/revenz/FileFlows/files/10147582/e863dde3-6ab3-4bca-9462-b4b5fcb7e959.log)

[Convert to MP4 H265.json.txt](https://github.com/revenz/FileFlows/files/10147574/Convert.to.MP4.H265.json.txt)

**Comment by ray73864** [comment]
![2022-12-04 08_18_01-FileFlows and 7 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/1343103/205467763-12c2a78e-e860-4654-a58c-3543073d4963.png)

More on mine, again, I fail to see how these are even duplicates, despite the thing saying they are.

When I select them and then click on 'process', it will successfully go through and process them all.

**Comment by cereal-ninja** [comment]
@ray73864  your issue sounds like this one: #355  fixed in version 1.06.  what version are you running?

**Comment by ray73864** [comment]
Ahh, I'm running 1.0.5.

Half the time I forget that FileFlows is even running since it just sits there doing its own thing.

**Comment by revenz** [comment]
can you test with 1.0.8, otherwise i'm closing this ticket.

**Comment by cereal-ninja** [comment]
to be clear - my issue isn't the same as @ray73864 , it's the same as @snwaine.  Am running 1.0.8.2176 and as you can see from screenshots the OutputPath field in the DB + log is incorrectly missing a forward slash between media & test. The MP4 file is created successfully from the flow but then it's marked as duplicated due to the incorrect OutputPath.

**Comment by lecerealkiller** [comment]
@revenz  any ideas on this? I can see in the logs + SQL Lite DB the output path is missing a forward slash in the path for first subfolder the library is in. It seems to happen primarily on the Windows 10 computer (not the internal node on the linux server). I have my media folder setup as a SMB Share.

From LOG:
```
2022-12-31 16:05:43.217 [INFO] -> Final Fingerprint: bb57070bd54647b19b702b63e92efb62c812967d0fc20cd189347726b1a56af1
2022-12-31 16:05:43.220 [INFO] -> Original Size: 2128864148
2022-12-31 16:05:43.223 [INFO] -> Final Size: 1826384401
2022-12-31 16:05:43.227 [INFO] -> Output Path: /mediatest/test2/Season 08/Brooklyn Nine-Nine - S08E02 - The Lake House - [Bluray-1080p][AC3][x265].mp4
2022-12-31 16:05:43.231 [INFO] -> Final Status: Processed
2022-12-31 16:05:43.647 [INFO] -> Connection_Closed
2022-12-31 16:05:43.727 [INFO] -> Final Fingerprint: bb57070bd54647b19b702b63e92efb62c812967d0fc20cd189347726b1a56af1
```

The correct path is /media/test/test2/Season 08/ or Z:\media\test\test2\Season 08\ (and the MP4 file actually is created there properly from the flow)

My docker compose is setup like this:
   ```
 volumes:
       - /opt/docker/fileflows/data:/app/Data
       - /opt/docker/fileflows/logs:/app/Logs
       - /opt/docker/fileflows/encoding:/temp
       - media_mount:/media
```

The path in the library setup is: /media/test/test2

The windows 10 machine has Z drive mapped to \\server\media & in Node MAPPINGS I have 
    Server \media = Node Z:\

Could the trailing backslash in the Node mapping be the problem?  I am noticing the in logs there are references to Z:\test... & some others Z:\\test...

**Comment by revenz** [comment]
``` The windows 10 machine has Z drive mapped to \server\media & in Node MAPPINGS I have:
Server \media = Node Z:\  ```

your mapping is wrong then.  mapping works effectively by replacing a string from one side with the other

so mapping \media to Z:\, would replace \media\something with z:\\something
in windows, it doesnt care about 2 slashes and will continue.

but then when mapping back, it would be z:\something, to \mediasomething

so your fix is to, map \media to Z:, or \media\ to z:\

**Comment by lecerealkiller** [comment]
> 

Yep - changing the Z:\ to Z: in the mapping seems to have done the trick! thx! 👍

**Comment by revenz** [comment]
closing as this ticket has too many conflicting data on it.  I believe #397 would solve the original issue mentioned in this ticket
