### ISSUE TITLE
Add Support for Users

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#369]
Add support so a username and password must be entered to use fileflows.

Also would need an api key for every user

**Comment by RVL-Solutions** [comment]
It undoubtedly has it's use-cases where something like this would be a logical feature, but other than in a business environment - I can't really come up with any...

If there really is a need for it - something like authelia would tick all the possible boxes perfectly fine.

**Comment by revenz** [comment]
authelia can be a pain to set up though.     i hear people ask for this from time to time, but there doesn't seem to be a big demand for it currently.

**Comment by revenz** [comment]
closing as lack of demand for this feature
