### ISSUE TITLE
Node can't process

### ISSUE THREAD

**Issue by reavessm** [revenz/FileFlows#37]
I have 1 server and 3 nodes and I can process fine on the server's internal node, but when I disable that, I can't get the node to process.  The node log shows this:

```
Info -> Making request[GET]: https://fileflows.domain.com/api/library-file/next-file?nodeName=fileflows-nodes-n67bk&nodeUid=7be8260e-bd29-4070-b137-b7f75955e2ae&workerUid=8eec7287-d138-43d6-b808-d10ca2f32612
Info -> Executing: /root/.dotnet/dotnet "FileFlows.FlowRunner.dll" "--uid" "4747f307-15e0-4c4c-9dce-cb5be8e4fdd5" "--libfile" "153c27d4-76b6-4644-9114-79e2c104069e" "--tempPath" "/app/temp" "--baseUrl" "https://fileflows.domain.com" "--hostname" "fileflows-nodes-n67bk" "--notserver"
Info -> Working Directory: /app/FileFlows-Runner
Info -> Making request[PUT]: https://fileflows.domain.com/api/library-file/153c27d4-76b6-4644-9114-79e2c104069e/full-log
Info -> Removing executing runner[1]: 4747f307-15e0-4c4c-9dce-cb5be8e4fdd5
Info -> Runner count: 0
```

I am running this on OpenShift 4.10 if that matters.

**Comment by revenz** [comment]
Have you configured the mappings for these external nodes?

**Comment by reavessm** [comment]
I have Server:/usr/local/bin/ffmpeg -> Node:/app/Tools/ffmpeg

**Comment by revenz** [comment]
You also need to map the folder/paths from the server to the node.

Eg on a docker server I may have 
/mnt/movies

But on my windows processing node I may have
\\tower\movies

And I could then have a "Copy File" node which copied the working file into 
/mnt/converted
On my server but on my node that path would be 
\\tower\converted

So my mapping would be 
![image](https://user-images.githubusercontent.com/958400/164948897-8f53b51d-c3ea-47f8-b538-f0d937e8ebda.png)

**Comment by reavessm** [comment]
That makes sense, the UI mentions mapping libraries but I thought that meant like dlls.  So I added Server:/app/media -> Node:/app/media, but I'm getting the same result.  Do the nodes need shared storage?  I think I assumed the server would push the data to the nodes.

**Comment by revenz** [comment]
No, no storage is shared.   The reason the server does not push data to the nodes, is then you have to read all the data on the server and then write all that data to that node.   Which is very time-consuming. 

So if you had a 50GB video file you would have to read that on the server (which may be on a different machine than the file) and then write that file to the node.  Then you would finally be able to process that file.  Which may require no processing at all so you wasted all that time.
If it did need processing, then you would then also need to upload that new file (if using copy/move) to the server, and then the server would have to then write to the server containing the file.

This is very likely a mapping issue.

**Comment by reavessm** [comment]
Yep, I mounted the storage as an NFS volume on both the server and the node, configured the node mapping of ffmpeg to point to `/usr/local/bin/ffmpeg` and everything is working as expected.

This software might take some getting used to but this flexible mapping should should make it easy to add my desktop to help out.

Thanks for all your help!  This already is a really solid program!

**Comment by revenz** [comment]
Glad you got it working.  I'll add better logging to make this kind of issue easier to diagnose,   this has just been a low priority until now due to most users (95%+) just using the internal node.

**Comment by revenz** [comment]
https://github.com/revenz/FileFlows/issues/39

To improve the logging
