### ISSUE TITLE
docker permissions are missing

### ISSUE THREAD

**Issue by axute** [revenz/FileFlows#373]
Two scripts are offered to upscale anime movies. However, both use a different Docker container.
Unfortunately, the fileflows image does not have permissions for the fileflows user.

the missing commands are:
```
groupadd docker
usermod -aG docker fileflows
```
(restart of the fileflows container is required if it is done when the container already exists)

**Comment by revenz** [comment]
another work around should be to just not set a PUID or PGID in the environmental variables.    but ill update the docker-entrypoint.sh to include this change aswell

**Comment by revenz** [comment]
done

was
```
useradd -u "${PUID}" -g $pgid $user
```
now
```
useradd -u "${PUID}" -g $pgid -G docker $user
```
