### ISSUE TITLE
[Feature Request] Better handling of Fail Flow Process Layout

### ISSUE THREAD

**Issue by saitoh183** [revenz/FileFlows#374]
When i file fails to process and you have a fail flow in place, there is zero quick indication the fail flow has ran. Under info you only get the Nodes of the Flow that failed to process.

What i think it should have:

- Files processed under Fail flow should be moved to a new section once they are processed...maybe called Failed Flow process ( im sure you could have a better name :) ) This way files that fail both would be a real Failed processing.
- under Info, add the fail flow process after the node that caused the fail.

In the current state, i need to click on  each failed entry, scroll the entire log to see if the Failed Flow worked.

**Comment by revenz** [comment]
1. any failed files go under the "Failed" section
2. the fail flow is intended to notify the user of a failure
3. Failures should not be common, if this is happening look at the root cause of these failures.

**Comment by saitoh183** [comment]
Ok well can you at least show that the fail flow nodes ran under the info section?
![image](https://user-images.githubusercontent.com/1534197/204068052-7823ffad-97aa-4de4-af0a-334a7383485a.png)

We should see the Fail Flow nodes after the failure node and be able to click on the output log icon like the rest instead of having to scroll the entire log to find the entry
