### ISSUE TITLE
MKV attached files being removed after Track Reorder 

### ISSUE THREAD

**Issue by FrequencyLost** [revenz/FileFlows#378]
Attached files within an MKV container, like font files, are being removed when they get processed through Track Reorder. 
This is for MKV > MKV flows and happens with both audio and subtile reorder.

Attachments can be viewed in MKVToolnix attachments tab, or gMKVExtractGUI

![Screen Shot 2022-12-04 at 22 02 27 pm](https://user-images.githubusercontent.com/28737028/206294292-a2f8b6b4-b07e-49b0-a79c-2000d74db193.png)
![Screen Shot 2022-12-04 at 21 55 43 pm](https://user-images.githubusercontent.com/28737028/206294316-8611c18c-fd84-4186-b962-22295e3db14e.png)
![Screen Shot 2022-12-04 at 21 55 24 pm](https://user-images.githubusercontent.com/28737028/206294333-5f4d493a-d7bd-454d-8c0b-2843c5e6b61c.png)
![Screen Shot 2022-12-04 at 22 25 04 pm](https://user-images.githubusercontent.com/28737028/206294442-18ce00c9-251b-47cb-ab39-b6e9c0b5fe6e.png)
[W - 01 [BD 1080P HEVC10 E-AC-3 Dual Audio]-002.mkv.zip](https://github.com/revenz/FileFlows/files/10180065/W.-.01.BD.1080P.HEVC10.E-AC-3.Dual.Audio.-002.mkv.zip)

**Comment by revenz** [comment]
done
