### ISSUE TITLE
Expanded Video Scaler Node Resolutions

### ISSUE THREAD

**Issue by mrtakaaxe** [revenz/FileFlows#379]
Within the Video Scaler Node, is it possible to add the ability to specify a desired height (keeping aspect ratio for width aka -2 or -1 as per documentation) or vice-versa for width, rather than the specific resolutions?

In addition, is it also possible to specify a alternative custom resolution not in the current list?  Maybe they want 240p or 360p for some really old 4:3 TV rips they can't find anymore.

**Comment by revenz** [comment]
the scaler, uses 
```
640:-2
1280:-2
1920:-2
3840:-2
```
So it scales the width, and the height is automatic.

If you want the inverse, then you can achieve this with a function node or a custom parameter
