### ISSUE TITLE
Deleting node from UI causes error loop

### ISSUE THREAD

**Issue by reavessm** [revenz/FileFlows#38]
When you delete a node from the UI, the node log looks like this:

```
Info -> Making request[GET]: https://fileflows.domain.com/api/node/by-address/fileflows-nodes-tdw7b
Info -> Error Body: Object reference not set to an instance of an object.
Failed to get node by address: Failed to register node: Object reference not set to an instance of an object.
at FileFlows.ServerShared.Services.NodeService.GetByAddress(String address) in C:\BuildAgent\work\FileFlows\ServerShared\Services\NodeService.cs:line 86
Error -> Failed checking enabled: One or more errors occurred. (Failed to register node: Object reference not set to an instance of an object.)
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at FileFlows.Node.Program.<>c.<Main>b__0_1() in C:\BuildAgent\work\FileFlows\Node\Program.cs:line 102
```

If you're open to suggestions (which its fine to say you're not), I think the node should try to re-register if it fails in this way, BUT the server should also prompt the user to confirm before accepting a node.  Right now anybody can point their node at my server and it auto accepts it.  It doesn't enable it, which is good, but it can at least clutter up the Nodes page.

Here is the function reporting the error.

https://github.com/revenz/FileFlows/blob/88c54824c59995baf0b198c95429214532030d98/ServerShared/Services/NodeService.cs#L71-L86

I know the "docker way" is to delete the container and recreate it, but a simple re-register would automate that.

Also, if you don't want to auto re-register the node, it should at least maybe kill itself so it's not just spinning like this.

**Comment by revenz** [comment]
Agreed, it should re-register it.   
I don't think it should prompt the user though, as then if the page is not opened, they will have no prompt, so then will need to go to a page to allow it which, effectively is what happens now when you have to enable it.

However, perhaps a new state of "Authorized" vs "Unauthorized" and you have to authorize any newly registered servers.

**Comment by revenz** [comment]
Decided against do an Authorized/Unauthorized state for now.   The whole API is completely open, there is no security, this is to simplify it and is not intended to be exposed.

So in order to make unauthorized/authorized actually work, authentication would first need to be implemented and then this would be become of that change.

I have fixed the exception that was thrown and updated the "Save" button in the Windows GUI to be "Save / Register".  So if the node is deleted, you just need to click the "Save / Register" button to re-register it.
