### ISSUE TITLE
Calculations in Custom Parameter Node

### ISSUE THREAD

**Issue by mrtakaaxe** [revenz/FileFlows#380]
Would it be possible to insert calculations into the Parameter field of the Custom Parameter node?  I'm thinking something similar to inserting current upstream variables but with math functions or other useful functions for example?  eg. "scale={Math.trunc(({vi.Width} / ( {vi.Height} / 400))/2)*2}:400" ... would result in "scale=800:400".

**Comment by revenz** [comment]
no, you would need to do this in a function node and create a new variable, then use that variable in field you want.
