### ISSUE TITLE
Turn off Default flag of Non-forced Subtitles

### ISSUE THREAD

**Issue by mrtakaaxe** [revenz/FileFlows#381]
Can we have an option... maybe in the Track Remover node as an option for Subtitle streams... where we can specify that subtitles have their default flag disabled.  I wish to keep all Eng subtitles but I'd like to not have them enabled by default.  I understand that this is achieved by the syntax: "-default_mode infer_no_subs"... not sure on the viability.  Of course, if possible, it'd be handy to have Forced Eng subtitles remain enabled but I'm not sure how viable that additional aspect is.

**Comment by GamerBene19** [comment]
This seems closely related to my issue #133. If time is invested here it might be worth to implement the "other" flags as well. For example MKVToolnix has these flags available:
![image](https://user-images.githubusercontent.com/20821976/207984302-0d992290-0ce7-4ed5-84cc-fe4ba2d140a6.png)

**Comment by revenz** [comment]
added to next version https://docs.fileflows.com/plugins/video-nodes/ffmpeg-builder/subtitle-clear-default
