### ISSUE TITLE
Lack of existing healthcheck when running in external processing node mode.

### ISSUE THREAD

**Issue by tobz** [revenz/FileFlows#382]
👋🏻 

As I've been trying to set up a deployment of FileFlows in a controller/worker scheme using the "external processing node" support, one thing I've stumbled on is a lack of exposed API for external processing nodes.

I run FileFlows in Kubernetes, where everything has probes for readiness/liveness, pointed at whatever healthcheck/status endpoint the application happens to have. For the FileFlows "controller", I just point the probes at `/api/status` which suffices as a healthcheck endpoint. However, this is missing when running in the "external processing node" mode.

I can manage to get around this by using command-based probes -- run a command instead of pinging an API -- and seeing if the `dotnet` process is even running. This works fine, but here's my potential ask, I suppose: can you see a future where there's an API endpoint when running in the "external processing node" mode?

While the command-based probes _do_ work, as mentioned, they're clearly only able to see that the `dotnet` process is running, but to say nothing of whether or not the process, is in fact, "live". A stripped down API that provided a similar `/api/status` endpoint, though, could provide both accurate liveness checking as well as potentially exposing other useful information.

I'm even happy to try and whip up a PR for this, but I mostly wanted to get your thoughts on this first, in case it was already something on your mind and you had a particular vision for what such an enhancement would/should look like.

**Comment by revenz** [comment]
I'll look into this.   shouldnt be difficult to add.   May limit it to linux (and docker) only hosts though, which would suit your use case.

**Comment by revenz** [comment]
next version will have 
localhost:5000/status

and return
```
{"StartedAt":"2023-02-06T19:30:29.3733407Z","UpTime":3.3912522,"ActiveRunners":0}
```

can override the 5000 port with --api-port 1234

**Comment by tobz** [comment]
@revenz Excellent! Looking forward to the next release. :)

Much appreciated.
