### ISSUE TITLE
File Owner/Permissions only set on temporary files

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#383]
My flow contains this structure:
![image](https://user-images.githubusercontent.com/20821976/208636495-c5853605-e37f-455f-a366-5c5f9422887f.png)
This means that the input file is simply copied to the output if the ffmpeg executor did not need to run. The file that gets copied does not get its owner (and permissions) set.

As far as I can tell this is caused by the if conditions of the `MoveFile` 
https://github.com/revenz/FileFlows/blob/1cf45c7b5faa9292f69288b3aa906ec4ec6f2058/Plugin/NodeParameters.cs#L576-L577
and `CopyFile` methods
https://github.com/revenz/FileFlows/blob/1cf45c7b5faa9292f69288b3aa906ec4ec6f2058/Plugin/NodeParameters.cs#L690-L691

Imo that the if is unnecessary since the "if windows" case is handled in `ChangeOwner`
https://github.com/revenz/FileFlows/blob/1cf45c7b5faa9292f69288b3aa906ec4ec6f2058/Plugin/Helpers/FileHelper.cs#L91-L92
and the "isTempFile" case is what's causing my issue.
Perhaps I'm overlooking something but I don't see why you'd only want to change the owner when moving/copying a tempFile since you are always setting the owner on the file at the target location (where it's irrelevant where the file came from).

The same logic also is contained in `SetWorkingFile`, but I think here it does make (more) sense since the working-file could be set to a input file which should likely not get it's owner changed.
https://github.com/revenz/FileFlows/blob/1cf45c7b5faa9292f69288b3aa906ec4ec6f2058/Plugin/NodeParameters.cs#L430-L434

**Comment by revenz** [comment]
fixed in next version, copy and move have removed that "if" statement check
