### ISSUE TITLE
[Feature Request] Option in settings to not delete temp directory if flow fails

### ISSUE THREAD

**Issue by devedse** [revenz/FileFlows#385]
As mentioned in my support request on discord it would be helpful to have a setting where you can keep the Temp directory if a flow fails.

I'm currently running into an issue where a specific flow fails to complete when running for 5 days. It's hard to see what's going wrong though because when I put a small file through the flow it all works fine.

**Comment by revenz** [comment]
done

**Comment by devedse** [comment]
Thanks! :)
