### ISSUE TITLE
[Feature] Setting the number of "Flow Runners" per flow, instead of per node

### ISSUE THREAD

**Issue by JoshLoecker** [revenz/FileFlows#386]
When using the internal processing node, for example, there's an option to set the number of flow runners. I have this set to 4 currently, due to the main flow I run being a little more process-heavy. 

However, occasionally I have a flow and its only job is to re-order audio tracks from least-to-most channels. This is an easy job, and I'd like to increase the number of workers for it, without having to modify the runners under Nodes > Internal Processing Node.

As the title states, would a feature be available to set the number of runners on a per-flow basis?

**Comment by revenz** [comment]
Its up to the node to request a file to process.  So it needs to be per node.  If the node is currently processing its maximum amount, it will not request a new file, so it couldn't ask for a new file.
