### ISSUE TITLE
High disk space usage in config directory

### ISSUE THREAD

**Issue by 6cUbi57z** [revenz/FileFlows#387]
I'm just looking at getting FileFlows running and have set it up in my kubernetes cluster with the volume attached for /app/Data for persistence. I initially granted a 250MiB volume just for testing expecting to need to increase it, but it was used much faster than I expected (within minutes of tinkering). I increased it to 1GiB but this is also filling up rather quickly.

Looking at the files, it seems that the config directory is configured for some kind of snapshotting? Presumably for the version history included in the premium tier. This snapshotting seems to copy a number of DLLs for the comic plugins which amount to ~26MB per snapshot. 

```
root@fileflows-0:/app/Data# du -hs Data/Config/*
26M     Data/Config/1
26M     Data/Config/10
26M     Data/Config/12
26M     Data/Config/13
26M     Data/Config/15
26M     Data/Config/17
26M     Data/Config/18
26M     Data/Config/19
26M     Data/Config/2
26M     Data/Config/4
26M     Data/Config/6
26M     Data/Config/7
26M     Data/Config/8

root@fileflows-0:/app/Data# du -hs Data/Config/19/*
12K     Data/Config/19/config.json
26M     Data/Config/19/Plugins
16K     Data/Config/19/Scripts

root@fileflows-0:/app/Data# du -hs Data/Config/19/Plugins/*
568K    Data/Config/19/Plugins/AudioNodes.ffplugin
140K    Data/Config/19/Plugins/BasicNodes.ffplugin
23M     Data/Config/19/Plugins/ComicNodes.ffplugin
1.8M    Data/Config/19/Plugins/ImageNodes.ffplugin
340K    Data/Config/19/Plugins/VideoNodes.ffplugin

root@fileflows-0:/app/Data# du -hs Data/Config/19/Plugins/ComicNodes.ffplugin/*
20K     Data/Config/19/Plugins/ComicNodes.ffplugin/ComicNodes.dll
16K     Data/Config/19/Plugins/ComicNodes.ffplugin/ComicNodes.pdb
80K     Data/Config/19/Plugins/ComicNodes.ffplugin/Docnet.Core.dll
4.0K    Data/Config/19/Plugins/ComicNodes.ffplugin/en.json
5.3M    Data/Config/19/Plugins/ComicNodes.ffplugin/pdfium.so
15M     Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes
552K    Data/Config/19/Plugins/ComicNodes.ffplugin/SharpCompress.dll
728K    Data/Config/19/Plugins/ComicNodes.ffplugin/SixLabors.Fonts.dll
1.8M    Data/Config/19/Plugins/ComicNodes.ffplugin/SixLabors.ImageSharp.dll
172K    Data/Config/19/Plugins/ComicNodes.ffplugin/SixLabors.ImageSharp.Drawing.dll

root@fileflows-0:/app/Data# du -hs Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/*
24K     Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/linux
5.9M    Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/osx
4.3M    Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/win-x64
4.0M    Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/win-x86

root@fileflows-0:/app/Data# du -hs Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/win-x64/native/*
16K     Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/win-x64/native/LICENSE
4.3M    Data/Config/19/Plugins/ComicNodes.ffplugin/runtimes/win-x64/native/pdfium.dll
```

**Comment by revenz** [comment]
every configuration change increased the config revision.  this is so a flow thats still running can access the resources/configuration it had when started.

if you dont want comics plugin filling up space, delete that plugin.

there is a worker that cleans up this directory, but its a scheduled worker and only deletes the configuration after a few days (as some processing can take many days to complete)

**Comment by 6cUbi57z** [comment]
Ah that makes sense and I missed the delete button on plugins as I was looking in settings. Really easy to re-add if I want it later as well.

Very nice!

**Comment by 6cUbi57z** [comment]
@revenz I deleted the comic plugin but it seems to be re-appearing on each restart?

**Comment by revenz** [comment]
true, the default plugins get recreated.... hmmm.   i may need to add a disabled state to plugins or make it smarter to only deploy plugins that are used.
