### ISSUE TITLE
Library file size setting incorrect

### ISSUE THREAD

**Issue by darwindogsters** [revenz/FileFlows#389]
(Great program by the way)

For some reason the library file size is not setting correctly:
![1](https://user-images.githubusercontent.com/75353407/211221006-4022b01d-54a7-4574-88bb-c277713654ca.png)

Then when re-opened
![2](https://user-images.githubusercontent.com/75353407/211221014-aa84a492-f1bc-4ca7-94b5-309c7205f1af.png)

Keeps reverting to 1705032704 bytes?

**Comment by revenz** [comment]
fixed.   UI was using int32 instead of a long (64) for this value, backend was using long.    
updated UI to use long and now is fixed.  will be in 1.0.9
