### ISSUE TITLE
Wrong date in file list table

### ISSUE THREAD

**Issue by deosrc** [revenz/FileFlows#391]
I've seen this a few times but it seems to be intermittent where the date seems to show as `<currentyear> years ago`.

![image](https://user-images.githubusercontent.com/50599779/212051851-509a9c6e-47e0-478d-8fb8-4147150f3866.png)

This screenshot is from the failed tab. I'm unsure if it appears on others.

I'm running in containers. If you let me know the command for the postgres client (assuming there is one installed) and the query to run, I'll check how the date is stored.

**Comment by revenz** [comment]
its a bug where the datetime is not set, and is 0000-01-01 (the default datetime value).   which is 2023 years ago.

**Comment by revenz** [comment]
now hides this date
