### ISSUE TITLE
[Feature Request] - Add "Remux to WEBM" Option 

### ISSUE THREAD

**Issue by GrimJu** [revenz/FileFlows#394]
As discussed on Discord:
Add a option for webm output similar to how mp4/mkv/mov are handled.

Things to look out for:
+ webm does not support h264/h265 only vp8/vp9/av1
+ webm does only support vorbis and opus audio
+ webm only supports webvtt subtitles

**Comment by revenz** [comment]
added in next version.  only does a remux to webm, same as remux to mkv/mp4/mov.  ie all this node does is set the extension to webm, then ffmpeg will work its magic.

up to the user to use other nodes to set video codec/audio/subtitles
