### ISSUE TITLE
[Feature Request] Processing Order by Oldest

### ISSUE THREAD

**Issue by luigi311** [revenz/FileFlows#396]
We need an option to add newly found items to the bottom of the processing order.

Right now i have sets being encoded one at a time because once i add in another set those are put at the top of the processing order causing the original set to remain incomplete until the new ones are all done or i manually go in and move the old set to the top. We need an option to put all newly found media at the bottom of the processing order so the existing order isnt messed up.

**Comment by revenz** [comment]
added to 1.0.8
