### ISSUE TITLE
Add bitrate to FFMPEG Builder: Video Encode

### ISSUE THREAD

**Issue by brianharwell** [revenz/FileFlows#398]
The Video Encode node only allows for the selection of a CRF or CQ setting using a slider. I am requesting that this node allow the user to specify the following:

1. CQ or CRF (existing)
2. Variable bitrate
3. Constant bitrate

It is possible (as per our discussion on Discord) to use the Video Codec node to achieve this, but as you pointed out this will only work if all workers have the same hardware. It turns out I was incorrect and not all of my workers have Intel Quick Sync, they are a mix of QSV and NVENC.

I also think using the Video Codec node is not easy because the user needs to know what commands to pass to ffmpeg.

If the Video Encode node supported the 3 settings mentioned above, it would be vastly easier to use.

**Comment by revenz** [comment]
wont fix.

If using the quality slider, this overrides any bitrate setting.  So you cannot use the Video Encode node.

You then have to use the Video Codec node and then you can use the preexisting Bitrate node.
