### ISSUE TITLE
Function nodes not working

### ISSUE THREAD

**Issue by thespinmaster** [revenz/FileFlows#4]
When adding a Function node and using any of the Video Templates (i.e. 'Video: Resolution"), the Processing fails.
The Log for the Flow shows:
2022-01-18 11:29:04.0166 - Error -> node returned error code:, Function
Attaching the VS debugger catches the following first chance exception.
![Screenshot 2022-01-18 234422](https://user-images.githubusercontent.com/97906905/150036702-5145be21-1491-4363-a84b-22ed1b5255f3.png)

**Comment by revenz** [comment]
Can you show me your flow?  vi comes from the "Video File" input node, so if you are using "Input File" that will be null at that point.

**Comment by thespinmaster** [comment]
Attached. Yes, I thought using an Input File node was the initial issue, but after switching to "Video File" I'm still getting the exception,
[Scratch.zip](https://github.com/revenz/FileFlows/files/7893121/Scratch.zip)

**Comment by revenz** [comment]
repo'd ill take a look

**Comment by thespinmaster** [comment]
Great. I think its the question marks in the java snippet(s) that's causing the following replace call to not work:
tcode.Replace("Variables." + k, "Variables['" + k + "']");

**Comment by revenz** [comment]
you're probably right, have to make it only replace the first match to Variables["vi"]?.whatever?.whatever.

**Comment by revenz** [comment]
fixed.  
```cs                
foreach (string k in args.Variables.Keys.OrderByDescending(x => x.Length))
{
    // replace Variables.Key or Variables?.Key?.Subkey etc to just the variable
    // so Variables.file?.Orig.Name, will be replaced to Variables["file.Orig.Name"] 
    // since its just a dictionary key value 
    string keyRegex = @"Variables(\?)?\." + k.Replace(".", @"(\?)?\.");
    tcode = Regex.Replace(tcode, keyRegex, "Variables['" + k + "']");
}

**Comment by revenz** [comment]
Pushed new builds of plugins which has this fix.  FF should auto-update with fixed version (if auto-update is on, otherwise manually trigger a  plugin update).

**Comment by thespinmaster** [comment]
Thanks, I can confirm that's fixed it. I think you may also need to add the same fix in the CodeEvaluatorController.
