### ISSUE TITLE
Hardware decoding

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#40]
It would be benefical if hardware decoding was also used to convert video files
USE NVIDIA HW DECODE  ''-hwaccel cuda -hwaccel_device {device}''

**Comment by reavessm** [comment]
If you throw in AMD decoding I can help test it.

**Comment by revenz** [comment]
You should be able to do this already, if you just add that to the video parameters of the node.   

Thats basically what this change will do, but it would test to see if there is AMD hardware first (if possible, will need to investigate first).

**Comment by revenz** [comment]
Now will check for hardware decoders  "cuda", "dxva2", "qsv", "d3d11va", "opencl" and use the first one that is available.   If none are available will not use hardware decoding.

Added as an option to FFMPEG Builder: Executor
