### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by NH-Networks** [revenz/FileFlows#406]
Ffmpeg sends all encoding to gpu 0 by default.. some sort of loadbalacing to have fileflows send encoding to least busy gpu would be nice 

`Encoding and decoding work must be explicitly assigned to a GPU when using multiple GPUs in one system. GPUs are identified by their index number; by default all work is performed on the GPU with index 0.`

**Comment by revenz** [comment]
Putting this here for reference

```
ffmpeg -hwaccel cuvid -c:v h264_cuvid -gpu 1 -i input.mp4 -c:v h264_nvenc output.mp4
```

-gpu is zero based

**Comment by revenz** [comment]
This can now be achieved with [FFmpeg Builder: Pre-Execute](https://docs.fileflows.com/plugins/video-nodes/ffmpeg-builder/pre-execute)

You  stored file (json/txt/whatever).   That can record what GPUS are in use.  Parse that file and decide which GPU to use.,  then Update that file and continue. Set the -gpu index.

Then once processing is done.   Run a function node to update the file to remove the gpu in use.
