### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80070008

### ISSUE THREAD

**Issue by CommandStorm5** [revenz/FileFlows#41]
OS: Ubuntu 20.04.4
Platform: Docker
Version: FileFlows Server 0.5.3 [latest]

Seems to be a DotNet problem with the latest docker image. Container enters a restart loop while spamming its log with:
```
Launching server
Failed to create CoreCLR, HRESULT: 0x80070008
Launching server
Failed to create CoreCLR, HRESULT: 0x80070008
Launching server
Failed to create CoreCLR, HRESULT: 0x80070008
```

**Comment by revenz** [comment]
I just installed a fresh copy of ubuntu 22 on my laptop.   

Installed docker through snap, ran this to install FileFlows docker

```
sudo docker run -d --name FileFlows -p 5000:5000 -v ~/docker/fileflows/data:/app/Data -v ~/docker/fileflows/logging:/app/Logs -v ~/docker/fileflows/temp:/temp --restart unless-stopped revenz/fileflows
```

Working fine, which suggests its an environmental issue.  What version of docker?

**Comment by CommandStorm5** [comment]
My favorite type of issue.
Docker version 19.03.13, build 4484c46d9d
Building a fresh container with the command above (slightly modified folder paths) fails with the same error.

**Comment by CommandStorm5** [comment]
Problem solved, my docker apt repo was removed at some point so docker was not up-to-date. Thx for reminding me to check that.
