### ISSUE TITLE
[Feature Request] Extend subtitle extractor node to be able to select to extract only "forced" subs.

### ISSUE THREAD

**Issue by Lokilicious** [revenz/FileFlows#411]
A valid use case for some users might be only to extract "forced" subs in a given language. It would be great if the subtitle extractor node had an option only to extract specific subs. (i.e. only english forced)

**Comment by Lokilicious** [comment]
For now i created a script which accomplishes what I need :) 

`/**
 * Description of this script
 * @output Description of output 1
 */
function Script()
{
    let subs = Variables.vi?.VideoInfo?.SubtitleStreams || [];
    let ffmpeg = Flow.GetToolPath('ffmpeg');
    let allowedLangs = ["ger", "eng"];
    let allowedCodecs = ["subrip", "mov_text", "ass", "ssa", "text"];
    let command = `-y -i "${Variables.file.FullName}"`;

    for(let sub of subs){
        Logger.ILog(sub);
        if(!allowedCodecs.includes(sub.Codec.toLowerCase())) {
            Logger.ILog(`Sub on stream ${sub.IndexString} has unallowed codec ${sub.Codec} ... Skipping!`);
            continue;
        }
        if(sub.Title.includes('SDH') || sub.Title.includes('HI')){
            Logger.ILog(`Sub on stream ${sub.IndexString} has unallowed keyword ${sub.Title} ... Skipping!`);
            continue;
        }
        let subsFile = Variables.file.FullName;
        if(allowedLangs.includes(sub.Language.toLowerCase())){
            Logger.ILog(`Found ${sub.Language} sub on stream ${sub.IndexString}`);
            subsFile = subsFile.split('.');
            subsFile[subsFile.length - 2] += `.${sub.Language.toLowerCase()}`;
            if(sub.Title.toLowerCase().includes('forced') || sub.Forced === true) {
                Logger.ILog('Sub is forced');
                subsFile[subsFile.length - 2] += `.forced`;
            }
            subsFile[subsFile.length - 1] = `srt`;
            subsFile = subsFile.join('.');

            command += ` -map ${sub.IndexString} "${subsFile}"`;
        }
    }

    command += ' -map 0 -c copy'

    Logger.ILog(command);

    let process = Flow.Execute({
        command: ffmpeg,
        arguments: command
    });

    return 1;
}`

**Comment by Lokilicious** [comment]
For now i created a script which does what I need :) 

https://pastebin.com/qBxVTHYs

**Comment by revenz** [comment]
you could make a PR for the script to 
https://github.com/revenz/fileflowsrepository

Just make sure you add comments and version number etc.   Then it will show up in the "Script Repository" for other users.

Put it in this folder
https://github.com/revenz/FileFlowsRepository/tree/master/Scripts/Flow/Video

**Comment by Pyro2677** [comment]
I have just started to use Fileflows. Where would one put this in the Flow? Before or after the subtitle removal?

**Comment by Pyro2677** [comment]
> For now i created a script which does what I need :)
> 
> https://pastebin.com/QTETu3Vz

Would you mind sharing your Flow? I'm trying to have forced subs as well.

**Comment by revenz** [comment]
added to [Subtitle Extractor](https://docs.fileflows.com/plugins/video-nodes/subtitle-extractor) to the next version
