### ISSUE TITLE
Changing a library name creates a new entry for storage statistics

### ISSUE THREAD

**Issue by SnippetSpace** [revenz/FileFlows#416]
I have 2 libraries: TV and Movies.
Initially the TV library was named "Video Library" (the default). When changing the name, instead of updating the storage statistics, it added a new entry:
![image](https://user-images.githubusercontent.com/917744/218871661-336bdfd3-6b73-4548-9a66-f887dca7f142.png)

Ask: base the storage saved categories on the underlying folder path, use the library name as a label only. This way when a library name changes it will update accordingly in the statistics. Additionally, this way if a different library folder gets added, with the same name, it could appear as a separate entry.

Bonus ask: be able to clear statistics.

**Comment by revenz** [comment]
fixed
