### ISSUE TITLE
[Suggestion] Add control in node options over GPU/CPU execution

### ISSUE THREAD

**Issue by SnippetSpace** [revenz/FileFlows#417]
Currently if the node has a GPU present, Fileflows seems to by default execute on GPU only. 
Giving control over GPU/CPU/QSV would allow for interesting options:
- CPU only would provide a higher quality conversion option.
- Using GPU only, my CPU usage is at around 30% (7700K). Adding CPU conversion in parallel with the ongoing GPU conversion could result in a faster overall library conversion speed.

**Comment by revenz** [comment]
Video Encode node had an option to use hardware encoder or not.
Video Codec wont use hardware encoder if you parameters dont specify it.  It will use it if using the magic strings "h265" "hevc" or "h264".  But you can use "libx265" for example to use cpu for h265

**Comment by SnippetSpace** [comment]
Still doesn't allow for simultaneous GPU/CPU on the same device

**Comment by revenz** [comment]
add Function node with 2 outputs
``` return Math.random() > 0.5 ? 1 : 2 ```
Then output 1 use CPU, output 2 use GPU
on average 50/50 would use CPU or GPU.

Or better yet, add logic to your flow to determine what to use.  Nothing is stopping you from using GPU or CPU, just have to make the flow to do it.
