### ISSUE TITLE
Suggestion: Add a convert subtitles node

### ISSUE THREAD

**Issue by GrimJu** [revenz/FileFlows#421]
Add a node that adds `-c:s` parameters to the ffmpeg executor.

Would be used for the new Remux to webm node that needs webvtt compliant subtitles.

Alternativly give the option for the custom parameter node that lets it add its parameters to the end of the ffmpeg call. This would allow custom parameter to override the `-c:s copy` parameter that the builder adds per default .

**Comment by revenz** [comment]
Fixed by #371
