### ISSUE TITLE
DB Upgrade Error - 108 to 109

### ISSUE THREAD

**Issue by kdackiw** [revenz/FileFlows#422]
1.0.8 to 1.0.9 upgrade of the DB throws this error.  Running under docker. 

2023-02-20 13:39:01.978 [INFO] -> ==================================================
2023-02-20 13:39:01.983 [INFO] -> Maximum concurrent database connections: 1
2023-02-20 13:39:02.152 [INFO] -> Database initialized
2023-02-20 13:39:02.702 [INFO] -> Current version: 1.0.8.2176
2023-02-20 13:39:02.717 [INFO] -> Upgrade running, running 1.0.9 upgrade script
2023-02-20 13:39:02.800 [ERRR] -> Error: One or more errors occurred. (SQL logic error
duplicate column name: Flags)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FileFlows.Server.Upgrade.Upgrade_1_0_9.AddLibraryFileFlags() in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 25
   at FileFlows.Server.Upgrade.Upgrade_1_0_9.Run(Settings settings) in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 18
   at FileFlows.Server.Upgrade.Upgrader.Run(Settings settings) in /src/Server/Upgrade/_Upgrader.cs:line 65
   at FileFlows.Server.Program.PrepareDatabase() in /src/Server/Program.cs:line 262
   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 108

**Comment by revenz** [comment]
fixed

**Comment by kdackiw** [comment]
Apparently not :-)  Just tried again - here are the docker logs:

{"log":"99 user exists\n","stream":"stdout","time":"2023-02-23T18:35:05.333064495Z"}
{"log":"changing owner of /app to: 99:100\n","stream":"stdout","time":"2023-02-23T18:35:05.333958291Z"}
{"log":"changed owner of /app to: 99:100\n","stream":"stdout","time":"2023-02-23T18:35:06.702460308Z"}
{"log":"Launching server as 'root'\n","stream":"stdout","time":"2023-02-23T18:35:06.702477624Z"}
{"log":"Info -\u003e Starting FileFlows 1.0.9.2211\n","stream":"stdout","time":"2023-02-23T18:35:06.788164637Z"}
{"log":"Info -\u003e Running inside docker container\n","stream":"stdout","time":"2023-02-23T18:35:06.788299211Z"}
{"log":"Debug -\u003e ENV.HOST_OS = Unraid\n","stream":"stdout","time":"2023-02-23T18:35:06.788358941Z"}
{"log":"Debug -\u003e ENV.S6_VERBOSITY = 1\n","stream":"stdout","time":"2023-02-23T18:35:06.788387899Z"}
{"log":"Debug -\u003e ENV.NVIDIA_VISIBLE_DEVICES = all\n","stream":"stdout","time":"2023-02-23T18:35:06.788414159Z"}
{"log":"Debug -\u003e ENV.PWD = /app/Server\n","stream":"stdout","time":"2023-02-23T18:35:06.788442325Z"}
{"log":"Debug -\u003e ENV.HOSTNAME = 0bde9646cb9e\n","stream":"stdout","time":"2023-02-23T18:35:06.788473824Z"}
{"log":"Info -\u003e ==================================================\n","stream":"stdout","time":"2023-02-23T18:35:06.788563807Z"}
{"log":"2023-02-23 11:35:06.788 [INFO] -\u003e ==================================================\n","stream":"stdout","time":"2023-02-23T18:35:06.788762718Z"}
{"log":"Debug -\u003e Arguments: --urls=http://*:5000 --docker\n","stream":"stdout","time":"2023-02-23T18:35:06.788783459Z"}
{"log":"Debug -\u003e ENV.HOST_CONTAINERNAME = FileFlows\n","stream":"stdout","time":"2023-02-23T18:35:06.78943182Z"}
{"log":"Debug -\u003e ENV.TZ = America/Edmonton\n","stream":"stdout","time":"2023-02-23T18:35:06.790601521Z"}
{"log":"Debug -\u003e ENV.MAIL = /var/mail/root\n","stream":"stdout","time":"2023-02-23T18:35:06.791673607Z"}
{"log":"Debug -\u003e ENV.PUID = 99\n","stream":"stdout","time":"2023-02-23T18:35:06.792914779Z"}
{"log":"Debug -\u003e ENV.LD_LIBRARY_PATH = /usr/lib/x86_64-linux-gnu\n","stream":"stdout","time":"2023-02-23T18:35:06.795565175Z"}
{"log":"2023-02-23 11:35:06.795 [INFO] -\u003e Starting FileFlows 1.0.9.2211\n","stream":"stdout","time":"2023-02-23T18:35:06.795757031Z"}
{"log":"Debug -\u003e ENV.DOTNET_CLI_TELEMETRY_OPTOUT = true\n","stream":"stdout","time":"2023-02-23T18:35:06.796495278Z"}
{"log":"Debug -\u003e ENV.NVIDIA_DRIVER_CAPABILITIES = compute,video,utility\n","stream":"stdout","time":"2023-02-23T18:35:06.797437383Z"}
{"log":"Debug -\u003e ENV.LIBVA_DRIVERS_PATH = /usr/lib/x86_64-linux-gnu/dri\n","stream":"stdout","time":"2023-02-23T18:35:06.798630533Z"}
{"log":"2023-02-23 11:35:06.798 [INFO] -\u003e Running inside docker container\n","stream":"stdout","time":"2023-02-23T18:35:06.799057664Z"}
{"log":"Debug -\u003e ENV.DOTNET_ROOT = /dotnet\n","stream":"stdout","time":"2023-02-23T18:35:06.799677297Z"}
{"log":"Debug -\u003e ENV.PGID = 100\n","stream":"stdout","time":"2023-02-23T18:35:06.800776079Z"}
{"log":"Debug -\u003e ENV.TCP_PORT_5000 = 5000\n","stream":"stdout","time":"2023-02-23T18:35:06.801935177Z"}
{"log":"2023-02-23 11:35:06.802 [DBUG] -\u003e Arguments: --urls=http://*:5000 --docker\n","stream":"stdout","time":"2023-02-23T18:35:06.802725942Z"}
{"log":"Debug -\u003e ENV.S6_CMD_WAIT_FOR_SERVICES_MAXTIME = 0\n","stream":"stdout","time":"2023-02-23T18:35:06.80303497Z"}
{"log":"Debug -\u003e ENV.TERM = xterm\n","stream":"stdout","time":"2023-02-23T18:35:06.804198852Z"}
{"log":"Debug -\u003e ENV.LANGUAGE = en_US.UTF-8\n","stream":"stdout","time":"2023-02-23T18:35:06.805407887Z"}
{"log":"Debug -\u003e ENV.LANG = en_US.UTF-8\n","stream":"stdout","time":"2023-02-23T18:35:06.806744658Z"}
{"log":"2023-02-23 11:35:06.806 [DBUG] -\u003e ENV.HOST_OS = Unraid\n","stream":"stdout","time":"2023-02-23T18:35:06.807049156Z"}
{"log":"Debug -\u003e ENV.SHLVL = 1\n","stream":"stdout","time":"2023-02-23T18:35:06.807576478Z"}
{"log":"Debug -\u003e ENV.SHELL = /bin/bash\n","stream":"stdout","time":"2023-02-23T18:35:06.808720648Z"}
{"log":"Debug -\u003e ENV.OLDPWD = /app\n","stream":"stdout","time":"2023-02-23T18:35:06.809847445Z"}
{"log":"Debug -\u003e ENV.PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin\n","stream":"stdout","time":"2023-02-23T18:35:06.810873348Z"}
{"log":"2023-02-23 11:35:06.810 [DBUG] -\u003e ENV.S6_VERBOSITY = 1\n","stream":"stdout","time":"2023-02-23T18:35:06.811042473Z"}
{"log":"Debug -\u003e ENV.HOST_HOSTNAME = FS\n","stream":"stdout","time":"2023-02-23T18:35:06.812092207Z"}
{"log":"Debug -\u003e ENV._ = /dotnet/dotnet\n","stream":"stdout","time":"2023-02-23T18:35:06.813013724Z"}
{"log":"Debug -\u003e ENV.HOME = /root\n","stream":"stdout","time":"2023-02-23T18:35:06.814081666Z"}
{"log":"2023-02-23 11:35:06.814 [DBUG] -\u003e ENV.NVIDIA_VISIBLE_DEVICES = all\n","stream":"stdout","time":"2023-02-23T18:35:06.814115578Z"}
{"log":"Debug -\u003e ENV.S6_STAGE2_HOOK = /docker-mods\n","stream":"stdout","time":"2023-02-23T18:35:06.815170588Z"}
{"log":"2023-02-23 11:35:06.816 [DBUG] -\u003e ENV.PWD = /app/Server\n","stream":"stdout","time":"2023-02-23T18:35:06.816882266Z"}
{"log":"Info -\u003e ==================================================\n","stream":"stdout","time":"2023-02-23T18:35:06.817318503Z"}
{"log":"2023-02-23 11:35:06.824 [DBUG] -\u003e ENV.HOSTNAME = 0bde9646cb9e\n","stream":"stdout","time":"2023-02-23T18:35:06.824988583Z"}
{"log":"2023-02-23 11:35:06.828 [DBUG] -\u003e ENV.HOST_CONTAINERNAME = FileFlows\n","stream":"stdout","time":"2023-02-23T18:35:06.828712049Z"}
{"log":"2023-02-23 11:35:06.832 [DBUG] -\u003e ENV.TZ = America/Edmonton\n","stream":"stdout","time":"2023-02-23T18:35:06.83216122Z"}
{"log":"2023-02-23 11:35:06.835 [DBUG] -\u003e ENV.MAIL = /var/mail/root\n","stream":"stdout","time":"2023-02-23T18:35:06.836007465Z"}
{"log":"2023-02-23 11:35:06.839 [DBUG] -\u003e ENV.PUID = 99\n","stream":"stdout","time":"2023-02-23T18:35:06.839711966Z"}
{"log":"2023-02-23 11:35:06.842 [DBUG] -\u003e ENV.LD_LIBRARY_PATH = /usr/lib/x86_64-linux-gnu\n","stream":"stdout","time":"2023-02-23T18:35:06.842968637Z"}
{"log":"2023-02-23 11:35:06.845 [DBUG] -\u003e ENV.DOTNET_CLI_TELEMETRY_OPTOUT = true\n","stream":"stdout","time":"2023-02-23T18:35:06.84577401Z"}
{"log":"2023-02-23 11:35:06.848 [DBUG] -\u003e ENV.NVIDIA_DRIVER_CAPABILITIES = compute,video,utility\n","stream":"stdout","time":"2023-02-23T18:35:06.84861698Z"}
{"log":"2023-02-23 11:35:06.851 [DBUG] -\u003e ENV.LIBVA_DRIVERS_PATH = /usr/lib/x86_64-linux-gnu/dri\n","stream":"stdout","time":"2023-02-23T18:35:06.851265294Z"}
{"log":"2023-02-23 11:35:06.854 [DBUG] -\u003e ENV.DOTNET_ROOT = /dotnet\n","stream":"stdout","time":"2023-02-23T18:35:06.854221277Z"}
{"log":"2023-02-23 11:35:06.856 [DBUG] -\u003e ENV.PGID = 100\n","stream":"stdout","time":"2023-02-23T18:35:06.856814241Z"}
{"log":"2023-02-23 11:35:06.859 [DBUG] -\u003e ENV.TCP_PORT_5000 = 5000\n","stream":"stdout","time":"2023-02-23T18:35:06.859744063Z"}
{"log":"Info -\u003e Maximum concurrent database connections: 1\n","stream":"stdout","time":"2023-02-23T18:35:06.861236248Z"}
{"log":"2023-02-23 11:35:06.862 [DBUG] -\u003e ENV.S6_CMD_WAIT_FOR_SERVICES_MAXTIME = 0\n","stream":"stdout","time":"2023-02-23T18:35:06.862639604Z"}
{"log":"2023-02-23 11:35:06.865 [DBUG] -\u003e ENV.TERM = xterm\n","stream":"stdout","time":"2023-02-23T18:35:06.865459068Z"}
{"log":"2023-02-23 11:35:06.869 [DBUG] -\u003e ENV.LANGUAGE = en_US.UTF-8\n","stream":"stdout","time":"2023-02-23T18:35:06.870136411Z"}
{"log":"2023-02-23 11:35:06.876 [DBUG] -\u003e ENV.LANG = en_US.UTF-8\n","stream":"stdout","time":"2023-02-23T18:35:06.876194759Z"}
{"log":"2023-02-23 11:35:06.883 [DBUG] -\u003e ENV.SHLVL = 1\n","stream":"stdout","time":"2023-02-23T18:35:06.883508119Z"}
{"log":"2023-02-23 11:35:06.886 [DBUG] -\u003e ENV.SHELL = /bin/bash\n","stream":"stdout","time":"2023-02-23T18:35:06.886743504Z"}
{"log":"2023-02-23 11:35:06.890 [DBUG] -\u003e ENV.OLDPWD = /app\n","stream":"stdout","time":"2023-02-23T18:35:06.890567275Z"}
{"log":"2023-02-23 11:35:06.893 [DBUG] -\u003e ENV.PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin\n","stream":"stdout","time":"2023-02-23T18:35:06.89334171Z"}
{"log":"2023-02-23 11:35:06.896 [DBUG] -\u003e ENV.HOST_HOSTNAME = FS\n","stream":"stdout","time":"2023-02-23T18:35:06.896209712Z"}
{"log":"2023-02-23 11:35:06.899 [DBUG] -\u003e ENV._ = /dotnet/dotnet\n","stream":"stdout","time":"2023-02-23T18:35:06.899176347Z"}
{"log":"2023-02-23 11:35:06.901 [DBUG] -\u003e ENV.HOME = /root\n","stream":"stdout","time":"2023-02-23T18:35:06.902052319Z"}
{"log":"2023-02-23 11:35:06.904 [DBUG] -\u003e ENV.S6_STAGE2_HOOK = /docker-mods\n","stream":"stdout","time":"2023-02-23T18:35:06.904948696Z"}
{"log":"2023-02-23 11:35:06.907 [INFO] -\u003e ==================================================\n","stream":"stdout","time":"2023-02-23T18:35:06.907718843Z"}
{"log":"2023-02-23 11:35:06.910 [INFO] -\u003e Maximum concurrent database connections: 1\n","stream":"stdout","time":"2023-02-23T18:35:06.910794438Z"}
{"log":"Info -\u003e Database initialized\n","stream":"stdout","time":"2023-02-23T18:35:06.976660509Z"}
{"log":"2023-02-23 11:35:06.994 [INFO] -\u003e Database initialized\n","stream":"stdout","time":"2023-02-23T18:35:06.994660016Z"}
{"log":"Info -\u003e Current version: 1.0.8.2176\n","stream":"stdout","time":"2023-02-23T18:35:07.287165244Z"}
{"log":"Info -\u003e Upgrade running, running 1.0.9 upgrade script\n","stream":"stdout","time":"2023-02-23T18:35:07.287644292Z"}
{"log":"2023-02-23 11:35:07.291 [INFO] -\u003e Current version: 1.0.8.2176\n","stream":"stdout","time":"2023-02-23T18:35:07.291376884Z"}
{"log":"2023-02-23 11:35:07.296 [INFO] -\u003e Upgrade running, running 1.0.9 upgrade script\n","stream":"stdout","time":"2023-02-23T18:35:07.297112961Z"}
{"log":"Error -\u003e Error: One or more errors occurred. (SQL logic error\n","stream":"stdout","time":"2023-02-23T18:35:07.327097297Z"}
{"log":"duplicate column name: Flags)\n","stream":"stdout","time":"2023-02-23T18:35:07.327115762Z"}
{"log":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n","stream":"stdout","time":"2023-02-23T18:35:07.327118238Z"}
{"log":"   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n","stream":"stdout","time":"2023-02-23T18:35:07.327119979Z"}
{"log":"   at System.Threading.Tasks.Task.Wait()\n","stream":"stdout","time":"2023-02-23T18:35:07.327121572Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrade_1_0_9.AddLibraryFileFlags() in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 25\n","stream":"stdout","time":"2023-02-23T18:35:07.32712305Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrade_1_0_9.Run(Settings settings) in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 18\n","stream":"stdout","time":"2023-02-23T18:35:07.327233048Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrader.Run(Settings settings) in /src/Server/Upgrade/_Upgrader.cs:line 65\n","stream":"stdout","time":"2023-02-23T18:35:07.327237939Z"}
{"log":"   at FileFlows.Server.Program.PrepareDatabase() in /src/Server/Program.cs:line 262\n","stream":"stdout","time":"2023-02-23T18:35:07.327239668Z"}
{"log":"   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 108\n","stream":"stdout","time":"2023-02-23T18:35:07.327241196Z"}
{"log":"Error: One or more errors occurred. (SQL logic error\n","stream":"stdout","time":"2023-02-23T18:35:07.327482693Z"}
{"log":"duplicate column name: Flags)\n","stream":"stdout","time":"2023-02-23T18:35:07.327488672Z"}
{"log":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n","stream":"stdout","time":"2023-02-23T18:35:07.327490389Z"}
{"log":"   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n","stream":"stdout","time":"2023-02-23T18:35:07.327492034Z"}
{"log":"   at System.Threading.Tasks.Task.Wait()\n","stream":"stdout","time":"2023-02-23T18:35:07.327493609Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrade_1_0_9.AddLibraryFileFlags() in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 25\n","stream":"stdout","time":"2023-02-23T18:35:07.327495035Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrade_1_0_9.Run(Settings settings) in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 18\n","stream":"stdout","time":"2023-02-23T18:35:07.327499639Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrader.Run(Settings settings) in /src/Server/Upgrade/_Upgrader.cs:line 65\n","stream":"stdout","time":"2023-02-23T18:35:07.327501382Z"}
{"log":"   at FileFlows.Server.Program.PrepareDatabase() in /src/Server/Program.cs:line 262\n","stream":"stdout","time":"2023-02-23T18:35:07.327502909Z"}
{"log":"   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 108\n","stream":"stdout","time":"2023-02-23T18:35:07.327504755Z"}
{"log":"2023-02-23 11:35:07.330 [ERRR] -\u003e Error: One or more errors occurred. (SQL logic error\n","stream":"stdout","time":"2023-02-23T18:35:07.330405844Z"}
{"log":"duplicate column name: Flags)\n","stream":"stdout","time":"2023-02-23T18:35:07.330422607Z"}
{"log":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n","stream":"stdout","time":"2023-02-23T18:35:07.330424852Z"}
{"log":"   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n","stream":"stdout","time":"2023-02-23T18:35:07.330426473Z"}
{"log":"   at System.Threading.Tasks.Task.Wait()\n","stream":"stdout","time":"2023-02-23T18:35:07.33042804Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrade_1_0_9.AddLibraryFileFlags() in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 25\n","stream":"stdout","time":"2023-02-23T18:35:07.330429565Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrade_1_0_9.Run(Settings settings) in /src/Server/Upgrade/Upgrade_1_0_9.cs:line 18\n","stream":"stdout","time":"2023-02-23T18:35:07.330431126Z"}
{"log":"   at FileFlows.Server.Upgrade.Upgrader.Run(Settings settings) in /src/Server/Upgrade/_Upgrader.cs:line 65\n","stream":"stdout","time":"2023-02-23T18:35:07.330432628Z"}
{"log":"   at FileFlows.Server.Program.PrepareDatabase() in /src/Server/Program.cs:line 262\n","stream":"stdout","time":"2023-02-23T18:35:07.330434201Z"}
{"log":"   at FileFlows.Server.Program.Main(String[] args) in /src/Server/Program.cs:line 108\n","stream":"stdout","time":"2023-02-23T18:35:07.330435692Z"}

**Comment by kdackiw** [comment]
When will the new image be available for a pull?

**Comment by revenz** [comment]
after I make an announcement.
