### ISSUE TITLE
V1.0.9 high bandwidth usage while idle

### ISSUE THREAD

**Issue by tinkerfish** [revenz/FileFlows#423]
After upgrading to V1.0.9 the fileflows process was using 800-900Mbps to my file server while no items were being processed. Reverting back to V1.0.8 resolved the issue
[FileFlowsDB-Feb21-02.log](https://github.com/revenz/FileFlows/files/10794953/FileFlowsDB-Feb21-02.log)
[FileFlows-Feb21-02.log](https://github.com/revenz/FileFlows/files/10794954/FileFlows-Feb21-02.log)

**Comment by achurak** [comment]
Same here, I jumped from 1.0.8 straight to 1.0.10 and noticed today that it's been saturating the read i/o on my drives ever since the upgrade 3-4 days ago, non-stop, while doing nothing at all. Full library scan is disabled, no idea what the hell it's been doing, nothing in the logs about that too. I killed it for now.

**Comment by 11harveyj** [comment]
same problem here. Not much in journalctl, this just repeats over and over again

> ar 12 12:05:56 resmediaserver FileFlows[424933]: Info -> Making request [GET]: http://localhost:5000/api/settings/current-config/revision
Mar 12 12:05:56 resmediaserver FileFlows[424933]: 2023-03-12 12:05:56.162 [INFO] -> Triggering worker: FlowWorker
Mar 12 12:05:56 resmediaserver FileFlows[424933]: 2023-03-12 12:05:56.163 [INFO] -> Making request [GET]: http://localhost:5000/api/settings/current-config/revision
Mar 12 12:05:56 resmediaserver FileFlows[424933]: Info -> No file found to process, status from server: NoFile
Mar 12 12:05:56 resmediaserver FileFlows[424933]: 2023-03-12 12:05:56.291 [INFO] -> No file found to process, status from server: NoFile
Mar 12 12:05:58 resmediaserver FileFlows[424933]: Info -> Triggering worker: SystemMonitor
Mar 12 12:05:58 resmediaserver FileFlows[424933]: Info -> Making request [GET]: http://localhost:5000/api/node/by-address/INTERNAL_NODE
Mar 12 12:05:58 resmediaserver FileFlows[424933]: 2023-03-12 12:05:58.169 [INFO] -> Making request [GET]: http://localhost:5000/api/node/by-address/INTERNAL_NODE
Mar 12 12:05:58 resmediaserver FileFlows[424933]: 2023-03-12 12:05:58.171 [INFO] -> Triggering worker: SystemMonitor
Mar 12 12:05:58 resmediaserver FileFlows[424933]: Debug -> Getting directory size (TEMP DIR) '/opt/FileFlows/Temp': 0 B
Mar 12 12:05:58 resmediaserver FileFlows[424933]: 2023-03-12 12:05:58.172 [DBUG] -> Getting directory size (TEMP DIR) '/opt/FileFlows/Temp': 0 B
Mar 12 12:05:58 resmediaserver FileFlows[424933]: Debug -> Getting directory size (LOGGING DIR) '/opt/FileFlows/Logs': 54.75 MB
Mar 12 12:05:58 resmediaserver FileFlows[424933]: 2023-03-12 12:05:58.177 [DBUG] -> Getting directory size (LOGGING DIR) '/opt/FileFlows/Logs': 54.75 MB
Mar 12 12:05:59 resmediaserver FileFlows[424933]: Info -> Triggering worker: FlowRunnerMonitor
Mar 12 12:05:59 resmediaserver FileFlows[424933]: 2023-03-12 12:05:59.377 [INFO] -> Triggering worker: FlowRunnerMonitor
Mar 12 12:06:00 resmediaserver FileFlows[424933]: Info -> Triggering worker: FileFlowsTasksWorker
Mar 12 12:06:00 resmediaserver FileFlows[424933]: 2023-03-12 12:06:00.217 [INFO] -> Triggering worker: FileFlowsTasksWorker

Will be downgrading for now

**Comment by 11harveyj** [comment]
Network traffic (as my media is connected via cifs), the dip just after 12:06 is where I stopped the fileflows service. The small increase in traffic at around 12:09 is where I started 1.0.8.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/7346615/224543692-25ff5162-89a1-4f6f-9840-656154c79135.png">

Noticed higher than normal CPU pressure too:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7346615/224543844-e3153207-ac20-4c88-a787-a65ca65ef619.png">

**Comment by revenz** [comment]
when 1.1.0 is out (currently in preview), can you recheck to see if this has been fixed.  leaving open for confirmation

**Comment by achurak** [comment]
> when 1.1.0 is out (currently in preview), can you recheck to see if this has been fixed. leaving open for confirmation

That seems to have helped. Don't see any heavy i/o while idle anymore. Thanks!

**Comment by achurak** [comment]
This problem is back in the latest preview version. I have to keep the app shutdown because of this more than I actually use it lately unfortunately.
