### ISSUE TITLE
Suggestion: specify webvtt as subtitle codec when using the remux to webm node

### ISSUE THREAD

**Issue by GrimJu** [revenz/FileFlows#424]
Add a case for webm destinations à la [mp4](https://github.com/revenz/FileFlowsPlugins/blob/develop/VideoNodes/FfmpegBuilderNodes/Models/FfmpegSubtitleStream.cs#L26).
In my opinion image based subtitles (which cannot be encoded to webvtt) should be discarded right there and then.

This would look something like this:
```
...
                case "webm":
                    {
                        if (!Helpers.SubtitleHelper.IsImageSubtitle(Stream.Codec))
                            results.Add("webvtt");
                        }
                    }
                    break;
...
```

**Comment by revenz** [comment]
Fixed by #371, FFmpeg Builder will now try to automatically convert subtitles if the container changes.   for webm, image subtitles are removed, the rest are converted to webvtt
