### ISSUE TITLE
Feature request: file tooltip

### ISSUE THREAD

**Issue by SnippetSpace** [revenz/FileFlows#427]
Many times the file name displayed is too long and thus you can't see/read the full text, especially file extensions that could be troublesome.
A tooltip on hover/touch with the full name would be useful

**Comment by SnippetSpace** [comment]
A simple title tag with the full name on each element with a file name should be the most basic and straight forward implementation

**Comment by revenz** [comment]
![Image](https://github.com/revenz/FileFlows/assets/958400/4320c704-97b3-482c-9789-09b2d957a5f2)


added to next release
