### ISSUE TITLE
Discord Plugin deserialization error after upgrade to MySQL

### ISSUE THREAD

**Issue by realashleybailey** [revenz/FileFlows#433]
After upgrading to MySQL database an error occurred with the deserialization of the Discord Plugins webhook details, the error is shown in the below image.

![image](https://user-images.githubusercontent.com/16636012/225780613-a8985ab3-68a3-4c87-a886-df5fa36ef336.png)

1) I have removed the plugin completely and reinstalled it
2) I have attempted to manually edit the DB portion where its stored and changed the value to  {"Json":""}, if you change the value to nothing then a configuration error occurs so the field must be JSON parsable, I then went back into the GUI and reinserted my webhook id and token
3) I have tried replacing the id and token to TEST and STRING:
{"Json":"{\u0022WebhookId\u0022:\u0022TEST\u0022,\u0022WebhookToken\u0022:\u0022STRING\u0022}"}
4) Clear the discord settings, save them and then reset them.

I have attached a copy of my Database

**Comment by revenz** [comment]
can you try the 1.1.0 preview build and see if this is still happening?  I tried to reproduce this and I was able to send discord messages without any issues.

**Comment by realashleybailey** [comment]
No worries, I will attempt a previous build and maybe a reinstall to see if that solves the issue then.
Thank you for having a look.
