### ISSUE TITLE
External Node shows "update required" even though Server and Node are on the Same Version.

### ISSUE THREAD

**Issue by Lokilicious** [revenz/FileFlows#434]
Server Version: [1.0.10.2222]
Node Version (according to installer): [1.0.10.2222]

Got the installer from https://fileflows.com/downloads and installed it with nssm according to the docs.

**Comment by realashleybailey** [comment]
Could this be due to the build number not matching in [Globals.cs](https://github.com/revenz/FileFlows/blob/a9bbbe88eb725d41cf300ddbef5fc15e4ab51d53/ServerShared/Globals.cs#L13)

`public static Version Version = new Version("1.0.10.0");`

**Comment by revenz** [comment]
nah that gets replaced during the build process, I just manually adjust that value during development when needed.   

Busy with a more serious issue regarding files being rescanned/slow UI atm, but Ill look into this after that.

**Comment by revenz** [comment]
made a slight change to hopefully address this issue, check 1.1.1 when its released and if it still happens reopen this ticket
