### ISSUE TITLE
"Replace original" node doesn't move a file but always uses a copy action

### ISSUE THREAD

**Issue by SamTRZ** [revenz/FileFlows#435]
https://docs.fileflows.com/plugins/basic-nodes/replace-original

This node copies the file always, which can take up a lot of time if the disk isn't really fast. We could also try to move the file if the original and temp file are on the same disk. As a fallback we could use a copy action if a move isn't possible.

**Comment by revenz** [comment]
I was mistaken, it already is doing a move operation

https://learn.microsoft.com/en-us/dotnet/api/System.IO.File.Move?view=net-6.0

**Comment by SamTRZ** [comment]
Hmm not sure why it's doing a copy action then instead with my setup..  Do you want me to try out some things or should I just close this issue?

**Comment by revenz** [comment]
Leaving open, I want to investigate some more.   But on first inspection it does look right.
