### ISSUE TITLE
How do I use pattern matching (FFmpeg audio converter)?

### ISSUE THREAD

**Issue by JoshLoecker** [revenz/FileFlows#441]
For example, I want to convert all 5.1-channel audio streams in a video file to AC3. Below is an example of what I have currently, but I don't know what the pattern matching works against.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/47901540/228320119-ee2ae997-b93a-4dbc-9c78-3fab423b815c.png">

Any help would be greatly appreciated! :)

**Comment by revenz** [comment]
says below the input, its a regular expression.  it will match again the title unless you specify it to match against "Use Language Code".
You cant use this node to only execute against 5.1 tracks, you would need to use a function node for that and do it in javasript.
