### ISSUE TITLE
Adjust Max-width of containers for better viewing experience on 1440p 16:9 class screens

### ISSUE THREAD

**Issue by GrimJu** [revenz/FileFlows#443]
Change `max-width` property of some container elements to a value around 2000px.
This would affect:
+ [.vi-container](https://github.com/revenz/FileFlows/blob/599cc1203f521c90bc2586b4a6b977d525324f6e/Client/Components/ViContainer/ViContainer.razor.scss#L9)
+ [.dashboard-wrapper](https://github.com/revenz/FileFlows/blob/0fcc4f2d1b7232446c0197d21a818fd952fe99ba/Client/Pages/Dashboard/Dashboard.razor.scss#L8)
+ and maybe [this](https://github.com/revenz/FileFlows/blob/5833a14fdab64409ea85cc539fe86e87f39d7380/Client/wwwroot/css/app.scss#L639) ,although I'm not sure where this is used

**Comment by revenz** [comment]
removed maximum width for flow table columns
added ability to specify a large width for columns (over 2100px)
added ability to change alignment of columns

Plugins, Nodes, Scripts pages now use centre alignment and large width for columns.  Other pages keep column sizes but now with no width limit.   

Dashboard left untouched and changing the maximum width of the dashboard woould actually break the dashboard
