### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by schklom** [revenz/FileFlows#445]
Seeing this project, I thought it could be useful for me on my Raspberry Pi, so I wanted to compile a Docker image for ARM. I looked for the Dockerfile, and now I don't understand what is going on. There was a Dockerfile, but it l looks like it was removed and the commit that removed it was deleted?

There are a few commits that reference a Dockerfile in this repository (https://github.com/revenz/FileFlows/commit/6c17239dcf4e4423a58ee620c157c01b5d376b0c for example), but it looks to me like that Dockerfile has disappeared without a trace.
From a search (https://github.com/revenz/FileFlows/search?q=dockerfile&type=commits), I cannot find the commit that removed it: the latest commit about it is https://github.com/revenz/FileFlows/commit/965cfee9fefe3ae868d10bf8cd802b997b2b2237 and only modified it.
Meanwhile, the DockerHub image was updated 2 days ago.

Can anyone help me understand what is going on? I am lost here.

Many thanks

**Comment by revenz** [comment]
dockerfile is in the private build repository.  if you need to create a personallised dockerfile just use the zip release which contains all the prebuilt binaries you need and create a dockerfile as you normally would.

**Comment by schklom** [comment]
@revenz There used to be a Dockerfile that built the binary, and now it is gone. I don't really understand, was this project open-source, but not anymore?

> just use the zip release which contains all the prebuilt binaries you need and create a dockerfile as you normally would

The prebuilt binary will not work on my Raspberry Pi because it uses an ARM CPU.
Normally, the purpose of the Dockerfile is to build the binary, not to simply download it.

**Comment by revenz** [comment]
This project has never been open source and the dockerfile never built the application.  It takes the build (which is produced by a team city server) and creates a docker from that.

The zip contains arm binaries.  It works fine on a pi.  I was running a pi node (not inside docker just the app directly on the host) up until recently.  The pi is just too under powered for any common usage.  It can do image and audio processing, but that's about it.

**Comment by schklom** [comment]
> This project has never been open source

Oh, my misunderstanding.

>  The pi is just too under powered for any common usage

I was planning to use it only as a server and host nodes to do the actual work.

> The zip contains arm binaries

I must have missed them, I will take a closer look. Thanks for the reply :)
