### ISSUE TITLE
Detection time not being saved correctly when choosing hours

### ISSUE THREAD

**Issue by azuravian** [revenz/FileFlows#446]
I set up a library and set it to use a detection time of less than 3 hours.  Of the 150 files in the folder, about 10 were in that range.  It kept not queuing any files, and when I went back, it was set to 3 minutes instead of hours.  No matter how many times I changed it, it always reverted back to minutes.  I could change it to days and it would save correctly, but if I then went back to hours, it would change to minutes.

**Comment by revenz** [comment]
fixed in 1.1.1, only issue was with "hours" it was using the same multiplier (1) as minutes days and weeks were fine
