### ISSUE TITLE
[Feature Request] *arr webhook support

### ISSUE THREAD

**Issue by deathbybandaid** [revenz/FileFlows#447]
All the *arrs (sonarr,radarr,lidarr,readarr,whisparr) support sending webhooks to other services. It would be convenient if FileFlows could receive these webhooks, and scan file paths given by the *arrs.

I asked via the servarr discord, and there is no clean example documentation of what this json output looks like. However I was referred to the Radarr `.cs` file as an example of the output.

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Notifications/Webhook/WebhookBase.cs

Besides the handling of filepaths, this api endpoint (to receive *arr webhooks) would also need to be able to handle the "test" webhook to verify that it works.

[Tdarr didn't have this functionality, so I had to write a script for it](https://github.com/deathbybandaid/tdarr_inform)

**Comment by revenz** [comment]
added
