### ISSUE TITLE
.HEIC images files supported?

### ISSUE THREAD

**Issue by mattdayinbound** [revenz/FileFlows#449]
Hello, just wondering if .HEIC images files are supported. I currently am using Immich as a way to back up my photos, but Apple only supports .HEIC image file formats. I tried to run it through the image format converter using every file format available,  but it always says "Execution error: Image cannot be loaded.". Let me know if you need any more information :)

![Screenshot 2023-04-07 165814](https://user-images.githubusercontent.com/130188707/230685649-a4096fcc-b611-4232-9db3-dac4daaa3823.png)

**Comment by mattdayinbound** [comment]
*edit: i didn't realize .HEIC is a proprietary apple image format

**Comment by revenz** [comment]
this was added when #460 was done recently.   it can convert from heic now, just not save to that format
