### ISSUE TITLE
Windows installation targets the wrong directory.

### ISSUE THREAD

**Issue by dellvenue7130** [revenz/FileFlows#451]
Der revenz,

it came to my attention, that a default installation of 'FileFlows' on windows installs all    
files in the **"C:\Users\{USER}\AppData\Roaming\FileFlows"** directory. As the name    
'AppData' already suggests, that directory is not meant to be used to install applications.   
Since the microsoft documentation is not very elaborated about the intended    
use, I'm giving you a third party explanation of the directories under the    
"C:\Users\{USER}\AppData\" path:

[What is AppData, and what are Local, LocalLow, and Roaming](https://www.xda-developers.com/appdata/)

Please change the program setup on Windows to use the **"C:/Program Files"** or the **"C:/Program Files (x86)"**   
folder for the program installation.

Kind regards, G. P.

**Comment by revenz** [comment]
Thats why it lets the user choose where they want to install it.  the default location will not be changed.  this keeps all data (plugins, scripts, database) in the one location.

If the user wants to install elsewhere they can

**Comment by dellvenue7130** [comment]
Dear revenz,

unfortunately that's not the way windows installations work. There is a reason why
program files and program data is separated in the windows OS.
There are also reasons why there is a "Windows" and "Program ..." directory
on the system drive of a window system.
(Did you read the article at 'xda-developers.com'?)
However, if you intend to establish your own standard I'm not in a position
to do anything about it. (But it will always show a lack of professionalism)

Kind regards, G. P.
