### ISSUE TITLE
Erroneous "Server.csproj" file.

### ISSUE THREAD

**Issue by dellvenue7130** [revenz/FileFlows#452]
Dear revenz,

the "Server.csproj" file in the "FileFlow/Server" project is erroneous and prevents VisualStudio   
from loading the project. The directory "Plugins" is named twice int the project file.   
The project does load after removing the entry which masks the quotes, but for some   
reason the "Plugins" directory is not part of the project.   
Did you delete, move, rename the "Plugins" folder or was the folder simply excluded   
from your commits?   

![image](https://user-images.githubusercontent.com/114184767/230790045-5d355c29-12e3-4745-a84e-6aa5b79bfc6e.png)

Kind regards, G. P.

**Comment by revenz** [comment]
You need to add that folder.
