### ISSUE TITLE
Docker - VersionMismatch

### ISSUE THREAD

**Issue by TuRDMaN** [revenz/FileFlows#453]
I have been using FileFlows in Docker for a quite a while, without issue.

Today, I looked at my Files page, and I have a ton of files in Unprocessed, but none of them are being processed.

Here is what I am seeing in my log:
```
2023-04-09 17:09:02.010 [INFO] -> Triggering worker: SystemMonitor
Info -> Making request [GET]: http://localhost:5000/api/node/by-address/INTERNAL_NODE
Info -> Triggering worker: SystemMonitor
2023-04-09 17:09:02.113 [INFO] -> Making request [GET]: http://localhost:5000/api/node/by-address/INTERNAL_NODE
Info -> Triggering worker: FlowWorker
Info -> Making request [GET]: http://localhost:5000/api/settings/current-config/revision
Info -> Triggering worker: FlowRunnerMonitor
2023-04-09 17:09:02.170 [INFO] -> Triggering worker: FlowWorker
2023-04-09 17:09:02.172 [INFO] -> Making request [GET]: http://localhost:5000/api/settings/current-config/revision
2023-04-09 17:09:02.174 [INFO] -> Triggering worker: FlowRunnerMonitor
2023-04-09 17:09:02.178 [INFO] -> Node 'FileFlowsServer' version '1.1.0.2255' is less than minimum supported version '1.1.0.2261'
Info -> Node 'FileFlowsServer' version '1.1.0.2255' is less than minimum supported version '1.1.0.2261'
2023-04-09 17:09:02.180 [INFO] -> No file found to process, status from server: VersionMismatch
Info -> No file found to process, status from server: VersionMismatch
```

It looks like it's complaining about a version mismatch between client and server? But I am, and have been, just running it all within a docker container. Nothing changed on my end between when it was working and what it is doing now.
I tried stopping and deleting the container, pulling revenz/FileFlows again and recreating the container, but it just does the same thing.

Is there something I can try to fix this?

**Comment by revenz** [comment]
server is version 1.1.0.2255 and node is 1.1.0.2261  so they wont work together.

Last 24 hours I've been pushing changes to try and fix a small issue some people were seeing with the memory cache introduced in 1.1.0.    Since this was related to that major change, and the only change being made, I have kept the 1.1.0 version number and just been pushing updates.

Try updating the docker container on the server now, it should grab the same version (or newer)

**Comment by TuRDMaN** [comment]
Thanks for the quick reply!

I deleted my container and tried pulling the image again, but it says it is up to date:
```
sudo docker pull revenz/fileflows
Using default tag: latest
latest: Pulling from revenz/fileflows
Digest: sha256:741b5f24ca147fa2c5837fbfc5be3834471e5f9e8783a7e7d7e6c20a71b8ecb5
Status: Image is up to date for revenz/fileflows:latest
docker.io/revenz/fileflows:latest
```

And it's still giving me the version mismatch error on restart.

**Comment by Lindsay-Mathieson** [comment]
Seeing the same issue - 35 unprocessed files, but nothing happening. Docker with server/internal node. Server and node versions are both 1.1.0.2261. Have recreated the container.

Would check the logs but keep get a "Unhandled error". Will post separately.

**Comment by Lindsay-Mathieson** [comment]
> Seeing the same issue - 35 unprocessed files, but nothing happening.

::cough:: some dumb ass may have forgot they paused processing. All working now, so nonissue for me. Sorry for the noise.

**Comment by TuRDMaN** [comment]
Update: 2023-04-10 12:24 EST

Seems to be working fine again now!

**Comment by TuRDMaN** [comment]
Seems to be broken again after the latest update

```
2023-04-10 16:54:36.190 [INFO] -> Node 'FileFlowsServer' version '1.1.0.2261' is less than minimum supported version '1.1.0.2263'
2023-04-10 16:54:36.192 [INFO] -> No file found to process, status from server: VersionMismatch
```

**Comment by revenz** [comment]
I'm not sure how you are updating your node, but that is getting updated sooner than the server.  update the server.

This isnt broken, its by design, the server and node versions must match

**Comment by revenz** [comment]
ah ok... that is odd.....  ill look into it

**Comment by revenz** [comment]
k, version 1.1.1 skips the version compare for the internal node.   when 1.1.1 is released try that (shouldnt be far away)

**Comment by 11harveyj** [comment]
Same issue here on 1.1.0.2264:

> Apr 13 16:18:32 resmediaserver FileFlows[89313]: 2023-04-13 16:18:32.956 [INFO] -> Node 'FileFlowsServer' version '1.1.0.2259' is less than minimum supported version '1.1.0.2264'
> Apr 13 16:18:32 resmediaserver FileFlows[89313]: Info -> No file found to process, status from server: VersionMismatch

Although I run directly, download the latest zip, unzip to /opt/FileFlows replacing all files, and then start the systemd service.

Will await v1.1.1
