### ISSUE TITLE
New Version Available message difficult to clear on mobile

### ISSUE THREAD

**Issue by QNetSo** [revenz/FileFlows#457]
Along the lines of this github issue [Cannot see space savings on touch devices](https://github.com/revenz/FileFlows/issues/418)

On mobile it is VERY difficult to close the notice about a new version being available. It's near impossible to hit the x. On my phone the majority of the time you end up hitting the link to the new version.

Could this be made more touch friendly? maybe make the X bigger?

moving the link to the version farther away from the X would at least make it less likely to accidentally hit it when you intend to hit the tiny x.
For instance New Version 1.1.0.xxx is now available x

@revenz  for ease you had said you could just disable the new version notification on mobile

**Comment by revenz** [comment]
hidden on small screens in the next version (1.1.1)
