### ISSUE TITLE
Suggestion: Video Multi-Method Assessment Fusion (WMAF) score plugin

### ISSUE THREAD

**Issue by HotBlack77** [revenz/FileFlows#459]
I mostly use FileFlows to do bulk video transcoding of a very wide range of files. While I have Flows that work very well for me (I love FlieFlows in general), I am often very cautious about if quality has been lost doing various transcodes. Nothing beats manual inspection but Netflix's Video Multi-Method Assessment Fusion (WMAF) tool does do a pretty good job as something that will produce a single number scoring the visual quality of video. Here is their own discription:

> VMAF is an [Emmy-winning](https://theemmys.tv/) perceptual video quality assessment algorithm developed by Netflix. This software package includes a stand-alone C library libvmaf and its wrapping Python library. The Python library also provides a set of tools that allows a user to train and test a custom VMAF model.

Its BSD licsened and source is on github: https://github.com/Netflix/vmaf

What I would love to see is a plugin that lets you caluclate the WMAF of a file in FileFlows. The idea being to calculate the WMAF score of a file before and after transcoding and to then keep the original file if the difference in scores is too large. 

I am not quite sure how the plugin system works, but once the libvmaf library is installed it can be called as just another ffmpeg option, see here: https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md

Would this be possible/interesting to add?

**Comment by revenz** [comment]
This would probably be best done via a script.    Scripts can be created/submitted to https://github.com/revenz/FileFlowsRepository
