### ISSUE TITLE
Allow specifying custom codecs in `Convert Audio` and simillar nodes

### ISSUE THREAD

**Issue by rtim75** [revenz/FileFlows#461]
My specific case is about `Convert Audio` node and aac codec: 

From ffmpeg on aac:

> FFmpeg supports three AAC-LC encoders (aac, libfdk_aac, aac_at) and two HE-AAC (v1/2) encoder (libfdk_aac, aac_at). The license of libfdk_aac is not compatible with GPL, so the GPL does not permit distribution of binaries containing incompatible code when GPL-licensed code is also included. Therefore this encoder have been designated as "non-free", and you cannot download a pre-built ffmpeg that supports it. This can be resolved by [compiling ffmpeg](https://trac.ffmpeg.org/wiki/CompilationGuide) yourself.

The fileflows already comes with `libfdk_acc` encoder support, so it would be if we could specify which specific encoder/codec we'd like to use. Right now it only allows selection from a drop-down list and when AAC is chosen it uses the defualt `aac` codec which is LC one.

I tried using `Custom Parameters` node, but it's placed before the main part of the command, meaning it gets overwritten by later `copy` parameters.

**Comment by revenz** [comment]
Can use the new [FFmpeg Builder: Pre-Execute](https://docs.fileflows.com/plugins/video-nodes/ffmpeg-builder/pre-execute) flow element in the next version to achieve this
