### ISSUE TITLE
Processed file output tab showing incorrect data when the flow did no replace

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#463]
I have a flow that compares pre/post size and discards the work if the size is larger. When reviewing these files the output tab is showing the output as having changed based on the encoding, but that file was discarded. 

[91c25876-1d92-4816-bbd7-ba4143b2dd32.log](https://github.com/revenz/FileFlows/files/114685
![SNAG-0000 13-05-2023 11 25 57 AM](https://github.com/revenz/FileFlows/assets/4150588/1c3bed59-4e7f-4ab1-bba7-eb7d8a239726)
![SNAG-0001 13-05-2023 11 26 01 AM](https://github.com/revenz/FileFlows/assets/4150588/96a82759-4dbd-4f76-9d13-2f73b7e3e201)

93/91c25876-1d92-4816-bbd7-ba4143b2dd32.log)
[91c25876-1d92-4816-bbd7-ba4143b2dd32.log](https://github.com/revenz/FileFlows/files/11468594/91c25876-1d92-4816-bbd7-ba4143b2dd32.log)

**Comment by revenz** [comment]
you have to re-read the video information, it takes the current video info it has as the final, so if  you just delete it after processing, it still has the deleted info as the current.
