### ISSUE TITLE
Processed file tab formatting broken in firefox 

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#464]
Firefox version 112.0.2

I do use ultra-wide resolution, but changing/scaling browser doesn't resolve this issue. Looks fine in chrome.

![SNAG-0002 13-05-2023 11 32 56 AM](https://github.com/revenz/FileFlows/assets/4150588/63a08d65-6f6a-47b2-8f0a-e8d7499590fd)
![SNAG-0003 13-05-2023 11 33 06 AM](https://github.com/revenz/FileFlows/assets/4150588/4ef23772-b312-4d8d-a19d-8b4adc159a67)

**Comment by revenz** [comment]
tried at resolution 5180x1440 and works fine.  I do remember fixing something similar to this  while ago, likely fixed then
