### ISSUE TITLE
Library value in Proceed file tab is showing wrong name

### ISSUE THREAD

**Issue by Sprooty** [revenz/FileFlows#465]
- In my processed file list, i am seeing items for Library = "Video Library"
- I have no Library  configured called "Video Library"
- I have been changing libraries around a bit

Suspect some files have been indexed twice under different library's? 

![SNAG-0007 15-05-2023 10 08 30 AM](https://github.com/revenz/FileFlows/assets/4150588/8ea77f7d-919e-4569-8be0-90bc0ee81c5b)
![SNAG-0006 15-05-2023 10 05 08 AM](https://github.com/revenz/FileFlows/assets/4150588/e1765048-ee09-40ed-a929-bd12f12a85b0)
![SNAG-0005 15-05-2023 10 05 02 AM](https://github.com/revenz/FileFlows/assets/4150588/dbea378f-8993-4807-8570-58bf03368ffe)
![SNAG-0004 15-05-2023 10 04 44 AM](https://github.com/revenz/FileFlows/assets/4150588/b7891dc0-f02c-41eb-9ca4-9efe85fc9255)

**Comment by revenz** [comment]
files cannot be indexed twice under two libraries, the name is a unique field in the db.  please open a support thread on the forum for this.  dont think its a bug
