### ISSUE TITLE
Feature: Add closed captions extraction, text file subtitle input to ffmpeg

### ISSUE THREAD

**Issue by djaydev** [revenz/FileFlows#47]
Some American TV has closed captions instead of subtitle tracks for recordings. Would it be possible to add the software "ccextractor" which is available in the ubuntu repos. The program takes out the closed captions and saves it to a text file. The follow-up step/process would be to add that text file as a subtitle input into ffmpeg.

CCExtractor syntax is simply
`ccextractor "videofile.mkv"`
The results of the ccextractor command is a new subtitle file with the same name as the video file, with the .srt extension.
`videofile.srt`

FFmpeg subtitle addition
`ffmpeg -i "videofile.mkv" -i "videofile.srt" ... -c:v ... -c:a... -c:s mov_text newvideofile.mp4`

Thank you

**Comment by revenz** [comment]
In the meantime, you can do this already (just not as neatly as dropping a node into the flow).

Just install ccextractor
then execute it via the Function node (look at a template example, eg the ffmpeg one).   
then execute ffmpeg again, once again using the function node with that ffmpeg command to add the new srt.  

I can easily add a node to add srt files to a video file.  
But the ccextractor one would require it to also be available on windows, is small enough for the installer, and license permits that.
