### ISSUE TITLE
Template and plugins list not loading

### ISSUE THREAD

**Issue by exico91** [revenz/FileFlows#471]
I dont know if its a bug o a problem in the configuration, I tried on two different servers to no avail

I installed FileFlows in Unraid via the docker system and configured my folders.

When i open it it is impossible to create a Flow, I think that it is supposed to load templates in the list but none appears and its a required value so I cannot save.

Same story with plugins, I tried to add a plugin but none loads. I tried to ping internet from the docker (after installing ping) and it works, also internet is not filtered.

I dont know what im doing wrong. I attached the logs and a screenshot
[FileFlows-May28-00.log](https://github.com/revenz/FileFlows/files/11585063/FileFlows-May28-00.log)

![fileflow](https://github.com/revenz/FileFlows/assets/97479177/f3c7b4bb-8292-482e-abf3-9fab05fb09c7)

**Comment by revenz** [comment]
plugins must be missing, try downloading those from the plugins page

**Comment by revenz** [comment]
its to do with the minimum supported version for the plugins having the wrong version.  looking into now

**Comment by revenz** [comment]
fixed,   download a fresh install/image
