### ISSUE TITLE
External node plex mappings failure

### ISSUE THREAD

**Issue by bolagnaise** [revenz/FileFlows#48]
When utilising an External node, the mapping for plex analyse fails to map correctly on completion.
[FileFlows.log](https://github.com/revenz/FileFlows/files/8598171/FileFlows.2.log)

![PLEX Plugin Settings](https://user-images.githubusercontent.com/6158616/166129861-3472590c-e71a-447e-b878-cb0be5e20d18.jpeg)

![Library Settings](https://user-images.githubusercontent.com/6158616/166129876-488c3a3c-be6e-48ef-9d32-d7f99c2f2ae6.jpeg)

![External Node Mappings](https://user-images.githubusercontent.com/6158616/166129885-90fad46c-66d6-4429-816b-309dfcbfb7aa.jpeg)

![File Failure Log Example](https://user-images.githubusercontent.com/6158616/166129902-baf6d3fa-b443-4236-8743-70ecb34a6679.jpeg)

**Comment by revenz** [comment]
Have you tried removing the trailing / and \ from the mappings?  Its trying to do a find a library based on a folder, folder names do not end with a / or \.
