### ISSUE TITLE
[Feature Request] Add compare node

### ISSUE THREAD

**Issue by DasPflanze** [revenz/FileFlows#481]
I find myself often in the situation that I have two different video files of the same movie (example: old plex dvr recording and a newer one, while one might have 5.1 sound or is in 1080p while the other one would only be 720p stereo). Now I have to manually decide which file I keep.
At the moment I'm looking at automated solutions for this problem and found FileFlows. It would solve all my problems if it could compare two files based on the Video Information.
My flow would look like this:

1. There are two folders named _Media_ and _Import_
2. The flow starts if a new file is added to the Import folder.
3. File Exists checks if there is another File with the same Name and folder structure in _Media_
4. If no, then it moves the file into _Media_ and stops, if yes it compares the two files
5. If the file is better than the existing one (higher bitrate, better resolution, more audio channels etc.) it replaces the existing file with the new one, if not it deletes the new file.

And at the same time, I could use all the video functions to recode the file if I decide to keep it. It would be really, really nice to have that functionality.

**Comment by revenz** [comment]
this is currently doable via a function or you could write a script to do it.   

1.  find the file (look at [Jint](https://github.com/sebastienros/jint) docs for how to do this)
2. if file not found, return
3. execute ffmpeg over other file (look at the function template of FFmpeg to learn how)
4. compare the data you want to compare
