### ISSUE TITLE
Export Node does not work in Unraid Docker

### ISSUE THREAD

**Issue by thespinmaster** [revenz/FileFlows#5]
**Steps to Repro:**
 In Unraid Open the Web UI for the FileFlows docker.
 Click on the Flows Tab.
 Select a Node in the Flows grid.
 Click on the Export button.
 
**Result:**
 A blank (black) page appears in FlowFiles.

**Expected Result:**
The Node to download (Ideally Prompting for a download location)

**Notes:**
Export does work when running FileFlows as a localhost (Should maybe prompt for download location rather than just download).
I suspect the problem may be a permissions issue.

**Comment by revenz** [comment]
fixed, wasnt just unraid, was an issue in all production builds which was not present in develop builds.   

I'll push a new build/version shortly after some testing.
