### ISSUE TITLE
Video Nodes: merge srt

### ISSUE THREAD

**Issue by revenz** [revenz/FileFlows#50]
as a user, it would be helpful if I could merge an srt or sub subtitle into a video file.

Either using the FFMPEG Builder, or just a dedicated node to do this.

**Comment by danmed** [comment]
To add some context to this i currently use the below bat file to process all MP4 files in a folder and (if there is an srt file with a matching name) mux them to an MKV and move the source files to a "MUXED" folder

`for %%a in ("*.mp4") do ( 
    ffmpeg -i "%%~na.mp4" -i "%%~na.srt" -c copy "%%~na.mkv"
    MOVE "%%~na.mp4" "F:\TORRENTS\COMPLETED\MUXED\%%~na.mp4"
    MOVE "%%~na.srt" "F:\TORRENTS\COMPLETED\MUXED\%%~na.srt"
)`

**Comment by revenz** [comment]
added to next version
