### ISSUE TITLE
Feature: Allow for hw decoding options in ffmpeg

### ISSUE THREAD

**Issue by Blackpaw** [revenz/FileFlows#51]
My specific use case - nvida.

You can specify hardware based decoding and cuda cpu offloading in nvidia enabled builds of ffmpeg, e.g
`-hwaccel cuda -hwaccel_output_format cuda `

But these have to be specified *before* the input file, which we can't currently do with FileFlows. If enabled, with my test file, FPS increases from 200fps to 400fps and cpu usage drops from 80% to 10% (for ffmpeg process). Particularly effective with multiple transcodes.

I'd suggest an extra field for pre input arguments and/or an advanced field where you can specify the entire argument list yourself, with substitutions for the filenames.

Currently I'm working around/testing this by specifying a batch file wrapper in the Node ffmpeg mapping. It works quite well.

**Comment by revenz** [comment]
Can you show me your current flow?

**Comment by Blackpaw** [comment]
> Can you show me your current flow?

Is this what you meant?

Flow: https://imgur.com/aCjoBah

VideoEncode: https://imgur.com/rwvlOSa

**Comment by revenz** [comment]
Thanks, if you switch to the FFMPEG Builder that has an option to use hardware decoding.

**Comment by Blackpaw** [comment]
> if you switch to the FFMPEG Builder that has an option to use hardware decoding.

Ah, thanks - I'll look into that.
