### ISSUE TITLE
Comskip Remove Ads: Remove ads with files that already has chapters (ad markers) mapped in it

### ISSUE THREAD

**Issue by Yankees4life** [revenz/FileFlows#69]
As its says in the title

The files that are generated by PlayOn usually has chapters titled "Video" and "Advetisement". I would like this plugin to remove the portion of the video that has the chapters titled "Advetisement". 

Pls and thank you

**Comment by revenz** [comment]
closing as lack of interest, I will relook at this if demand arises.   However, this could be achieved with a script
