### ISSUE TITLE
Suggestion; Node to detect and delete end credits / closing credits.

### ISSUE THREAD

**Issue by cld96** [revenz/FileFlows#70]
As the title says, a node that can detect and delete the end credits (aka closing credits).

One issue with this could be that it in certain cases cutting out the end credits would also cut out the post credit scenes (often seen in Marvel movies the hidden gems in the very end). This was briefly discussed on the File Flows Discord.  

Even so, applying a feature like this to tv-shows alone could reduce my entire library space requirement significantly and that just by removing minutes of each episode that no one ever watches.

**Comment by cld96** [comment]
Could it be possible to seek and remove black and white frames in reverse up until none black and white frames is detected? 
Thus removing useless end credits without the risk of losing anything of value.

**Comment by revenz** [comment]
wont do for now, may one day do though and will create a new ticket for it.
