### ISSUE TITLE
Suggestion: Update button in update notification

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#71]
as a user, I would like to be able to update FileFlows using the top notification bar.

If I have auto-updates turned off, being able to update from this notification means I can choose when and which updates I want to install, instead of having all updates automatically installed.

**Comment by revenz** [comment]
Likely, will have a link in notifcation bar to settings page which will have an "Download Update" from there.   This would also allow a user to immediately download an update without having to wait the ServerUpdater worker to run.

**Comment by revenz** [comment]
added button under settings to check for an update now
![image](https://user-images.githubusercontent.com/958400/173172351-84288d93-681d-4a38-af84-1aff30e7256d.png)
