### ISSUE TITLE
Minor Bug: Library Creation - No Flow Available to Select

### ISSUE THREAD

**Issue by Emalton** [revenz/FileFlows#72]
If the only Flow that you have created is "Flow Failure", it will still (almost) let you create a library and the instructions n creating the flow will be gone. Creating just the Flow Failure satisfies the requirement to advance to the next step, even though it shouldn't.

See the below screenshot - the only Flow I created was the "Flow Failure" and it let me get this far. Just a really minor bug - the `ConfiguredStatus` changes (Dashboard.razor) because it thinks you properly completed the first step so the instructions disappear.

I originally was going to submit a PR but I'm not smart enough to figure out how to fix it, haha

![image](https://user-images.githubusercontent.com/9328458/170890227-a1a3ef1f-7334-4812-832f-ce377de56e95.png)

**Comment by revenz** [comment]
Won't fix
