### ISSUE TITLE
Suggestion: System shutdown on queue completion (server - Windows)

### ISSUE THREAD

**Issue by cevadau** [revenz/FileFlows#74]
I would like to request the option to be able to shut the system down on the completion of a queue - with the possibility of adding a time delay.

**Comment by revenz** [comment]
Should this timer start only after a file has been processed?  
Or should the timer start as soon as the app is started? 

ie, say you have a shutdown timer of 30minutes, do you have to wait for a file to process to shutdown, or as soon as FileFlows start, it starts the timer, and only when a file is queued does the timer restart.

**Comment by cevadau** [comment]
probably best to wait for completion of file processing, just so the system doesn't shutdown mid process

**Comment by revenz** [comment]
I mean, if there is nothing to process when FF starts, do you want to wait until it found something, or do you want it to start the timer straight away?

I.e. you may have started it up to set something up.

**Comment by cevadau** [comment]
if there's nothing in the queue, start the timer straight away

**Comment by revenz** [comment]
This can be done via a [Task](https://docs.fileflows.com/tasks)
