### ISSUE TITLE
Exclude or include files by age

### ISSUE THREAD

**Issue by iamwoz** [revenz/FileFlows#75]
Looking for a method to filter files by age. eg:

1. within last xx days
2. xx days old

am I missing something?

**Comment by revenz** [comment]
this is a good candidate for the new Scripts feature I'm working on for the next release, have been discussing that on the discord channel with some previews of what it will be.   

So in 0.7 there will be a script now to do this test.

**Comment by iamwoz** [comment]
Did this get implemented @revenz? I can't see an age script in Scripts in 0.7. Cheers
