### ISSUE TITLE
Reduce drive thrashing

### ISSUE THREAD

**Issue by iamwoz** [revenz/FileFlows#77]
Just started using FileFlows and its fantastic!

Is it possible to introduce a method to mitigate drive thrashing?

My nodes and runners appear to be processing my library in alphabetic order. This is also generally the order that my movie media files are stored on my drives. So although I have a powerful server I have to limit the # of runners because they are often all writing back to the same hard drive.

If we had a method to avoid drive thrashing I'd be able to process my library much faster since I have 26 drives in this server.

![image](https://user-images.githubusercontent.com/85816876/171092792-dd44e23f-760d-4284-a855-c5fe9ac6e361.png)

**Comment by revenz** [comment]
what is available now is node scheduling, library scheduling, and priority for libraries and you can manually reorder files once queued.

how do you propose to solve your issue?   one way could be multiple libraries, then use multiple processing nodes.

or a more complex solution could be multiple libraries, but make it so libraries of same priority files are processed one library at a time, so libA file 1, then libB file 1, then libC file 1, then libA file 2 etc

**Comment by iamwoz** [comment]
Yeah no easy solution for sure. Was hoping for a [randomise] button on the library file list or as an option for the [video file] input block at the start of the flow. 

![image](https://user-images.githubusercontent.com/85816876/171118765-303c07c6-cc5e-4669-85a0-50117e152f05.png)

**Comment by iamwoz** [comment]
Maybe a button at the top of the library list for date field (created) - assuming you collect that when scanning the library - that allows us to sort the library by newest first. That way for bulk processing of existing media collections we are working on the most recent files first. :-)

![image](https://user-images.githubusercontent.com/85816876/171121465-7f6e43dc-beb5-4f19-ae0a-b82e0f451fba.png)

**Comment by revenz** [comment]
thats sounds like a good plan, ill add an option to a library to process files in the date created.    look at an option like
Processing Order: When Found | Date Created | Random
random would mean the order in the list wouldn't be correct, as it would just do a randomize when the node requests the next file.

I'll have a play

**Comment by revenz** [comment]
added to next version
