### ISSUE TITLE
Not able to access webgui

### ISSUE THREAD

**Issue by jfishie** [revenz/FileFlows#78]
Recently installed FileFlows using docker-compose on synology. I am running a handful of other containers but I cannot load the FileFlows web-interface on any port that I try. 

The container is up and running on my synology but I cannot access it,

  fileflows:
    container_name: fileflows
    image: revenz/fileflows
    restart: unless-stopped
    environment:
      - TZ=Pacific/Auckland
    ports:
      - 8263:8263
    volumes:
      - /volume1/docker/appdata/fileflows/data:/app/Data
      - /volume1/docker/appdata/fileflows/logs:/app/Logs

**Comment by revenz** [comment]
Not sure where you got port 8263 from, the docker container listens on port 5000 ( every page I can checked fileflows.com/downloads, hub.docker.com/revenz/fileflows) show port 5000.

If there's somewhere incorrect let me know and I'll update it.
