### ISSUE TITLE
Only attempts to use internal node

### ISSUE THREAD

**Issue by jferris-** [revenz/FileFlows#8]
There is no documentation I can find on the node setup process apart from [this ](https://fileflows.com/downloads#instructions)but I believe I have set it up correctly.

Looking at the server log though, there is no attempt to use the node. Only the internal node.

With nothing showing in the log related to the external node and no documentation, how can I attempt to resolve this issue?

**Comment by revenz** [comment]
what does the node log file say?

**Comment by jferris-** [comment]
> what does the node log file say?

`https://github.com/revenz/FileFlows/issues/8#issuecomment-1048154789`
on repeat

**Comment by revenz** [comment]
thats the server log, what does the node log say?

**Comment by jferris-** [comment]
Removing the node from the webui and then re-adding it by applying the settings on the node software resolved the issue.

Thank you for time and especially thank you for the project!

**Comment by revenz** [comment]
glad you got it working.  curious as to why it wouldn't work without removing/readding. but oh well, working now :)

**Comment by tupcakes** [comment]
for me it was because C:\Users\username\AppData\Local\Temp\FileFlows didn't exist. once I created that it started working.
