### ISSUE TITLE
Suggestion: pause processing button

### ISSUE THREAD

**Issue by iamwoz** [revenz/FileFlows#84]
There's times when I'd like to be able to pause all processing and then resume it.

Even better if the pause button had an option for pausing specific nodes or all nodes (incl internal)

**Comment by revenz** [comment]
I can add a "Pause" / "Resume" but this won't/can't pause the current flow runners, but it will prevent others from starting.

Is that acceptable?

**Comment by iamwoz** [comment]
That'd be perfect thanks @revenz - gotta be better than me stopping the container temporarily

**Comment by revenz** [comment]
my current work around is just going to the nodes page and disabling my nodes.   it hasn't bugged me enough to put a pause button on it.... yet... :D 
try get this into a 0.7.1

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/172104973-e1dc6f8f-1d6a-4808-98bd-85bf0534e5d3.png)

Added button to dashboard page in the next version to pause/resume processing.

![image](https://user-images.githubusercontent.com/958400/172105049-51088fcc-ee6a-4fd0-897a-fdb07dbe8587.png)
mobile view

**Comment by revenz** [comment]
Going to extend this so it prompts you for how long you want it to pause for
[x] Until I resumt
[x] For [x] Minutes

something like that.

**Comment by revenz** [comment]
added dialog to select how long to pause for
![Uploading image.png…]()
