### ISSUE TITLE
[enhancement] Request that node communicate completion

### ISSUE THREAD

**Issue by jferris-** [revenz/FileFlows#9]
It would be great if the node reported to the server once it has completed processing the file.

I noticed that if the node software is closed, the server just takes whatever was processed of the file and considers it done, potentialy replacing the original file with a unfinished clipped file.

It's some great software but unusable IMO until this is resolved.

**Comment by revenz** [comment]
thats not how it works at all.   
all files that are created are created in the temporary directory.   when  a new temp file is created (as you may be doing another node, eg encode to remove subtitles), it will delete the previous temp file (only if its in the temp folder).   
it will only replace the original file if you use the "Replace Original" node or use a "Move" node.   if the processing node dies half way through, it wont replace the original.

also it does report to the server when a runner is completed.  this is how it then start to process another file.

Where is your server running?  where Is your node running?   can you post your node log?

The vast majority of users just use the internal processing node, so the extra nodes do not have a lot of testing at the moment.  Ive done testing, and ran a bunch of files through, but I don't daily drive a node, i do daily drive the internal node.

The internal node acts fairly similar to an external node, however there's mapping involved, different hardware, calls are done the same way to the server to report start/progress/completed/error.

**Comment by revenz** [comment]
closing as no update from user
