### ISSUE TITLE
Success notification has wrong icon

### ISSUE THREAD

**Issue by GamerBene19** [revenz/FileFlows#94]
When a operation was successful (e.g. duplicating a flow) the notification still has the cross icon.
![image](https://user-images.githubusercontent.com/20821976/172125392-2bec49ee-9422-439d-885d-ef4afb831ede.png)

**Comment by revenz** [comment]
That "X" is actually the close icon. 

But you are right, its confusing, and should be changed for the colour blind.   

I'll move the x and add unique icons for success/failure/warning

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/173171728-2a7c6102-ea6e-48f9-afbf-18b31afa0088.png)

fixed in next version
