### ISSUE TITLE
Logging switch not working

### ISSUE THREAD

**Issue by iamwoz** [revenz/FileFlows#95]
My container log is filled with constant DBUG messages

![image](https://user-images.githubusercontent.com/85816876/172478481-fa1f49cb-5952-414e-b13c-4c723c1ce3bb.png)

Even though Log Queue Messages is disabled

![image](https://user-images.githubusercontent.com/85816876/172478613-1b39780c-7744-4266-819a-4f8f7b8af659.png)

Wonder if this constant activity is contributor to: https://github.com/revenz/FileFlows/issues/93

**Comment by iamwoz** [comment]
Some pretty good log sizes in the container:

![image](https://user-images.githubusercontent.com/85816876/172478987-5f71aee0-29b7-4fce-b18c-1155ef716978.png)

**Comment by iamwoz** [comment]
@revenz where do you prefer stuff like the above - github or forums?

**Comment by revenz** [comment]
here or the forum, both are good.   just not on reddit.   or unraid forum.  if posted on reddit/unraid, ill likely not see it or respond.   just too many places to check, so going with the 3, discord, fileflows forum and github.   

And ignoring any PMs from anyone who isnt a patreon :P   just incase a non-patreon is reading this.  

But on topic, regarding log file size, yes I'm going to be working on this soon, already created a ticket.

The switch should work (is on my machine, but I'm using mysql which may have somethign to do with it), but obviously its not, so I'll take a look.

**Comment by revenz** [comment]
Was wondering why its working fine for me
![image](https://user-images.githubusercontent.com/958400/172949869-9eebf4cb-6836-486a-90d5-9ffeccf9b49b.png)


The UI setting was inversed.   fixed in 0.7.1, in 0.7.0 turn it on to turn it off
