### ISSUE TITLE
VideoEncode Node feature Request: Already in codec output

### ISSUE THREAD

**Issue by Blackpaw** [revenz/FileFlows#96]
Unlike the "Video Codec" node, the VideoEncode node will encode a file, even its already in the desired codec. It would be nice to have a similar flow to "Video Codec"

**Comment by revenz** [comment]
I need to cull some nodes, but this would cause upgrade issues for some users, but it needs to be done.   Likely move them to a legacy plugin so people can still use them for a version or 2 to give them a chance to upgrade.

I suspect you're talking about the "FFMPEG Builder" nodes (those one will remain the other ones will likely be the culled out).    

So, "FFMPEG Builder: Video Encode" will do a force encode, as its a quality slider, often you will go from h265 to h265 just with a higher level of compression for example. 

So in that case you can use a "Video Codec" (logic node to detect the codec) or a "Video Has Stream" (another logic stream to look at video codec) to determine if it should run.


So, I guess what you are asking for, is to add an option to "FFMPEG Builder: Video Encode" for "Don't encode if already in codec" ?

**Comment by Blackpaw** [comment]
> So, I guess what you are asking for, is to add an option to "FFMPEG Builder: Video Encode" for "Don't encode if already in codec" ?

Yes, but reconsidering that - I already had a VP9 via the general "Video Codec" check node and I just added hevc to that for the desired behaviour.

Probably best not to overcomplicate the VideoEncode node. Which, BTW,  I like to use because it abstracts the hardware acceleration, I can use the same flow for NVidia and QSV processing nodes.

Thanks!

**Comment by revenz** [comment]
so close as not required?

**Comment by revenz** [comment]
its fine, no worries
