### ISSUE TITLE
Suggestion: Custom/Scripted FFMPEG Builder Node

### ISSUE THREAD

**Issue by Tim-Radcliffe** [revenz/FileFlows#97]
It would be useful to be able to insert custom settings into an FFMPEG Builder flow.

For example, a script could identify audio streams 2, 3 and 5 to be deleted.

There is currently no way of inserting custom scripted changes into the FFMPEG Builder execution run.

**Comment by revenz** [comment]
You can already, its just you cant into a InputNumber as it wont allow the variables {} to be inserted as those are text and not a number.

I'll likely expose the FFMPEG Builder object itself into the Variables and make it so you can make changes to that via a function node.

**Comment by revenz** [comment]
Added to 0.9.1

Sample of how to disabled a track from the output

This disables all subtitles and all but first audio
```
for(let i=1;i<Variables?.FfmpegBuilderModel?.AudioStreams?.length;i++)
{
	let as = Variables.FfmpegBuilderModel.AudioStreams[i];
	as.Deleted = true;
}
for(let i=0;i<Variables?.FfmpegBuilderModel?.SubtitleStreams?.length;i++)
{
	let sub = Variables.FfmpegBuilderModel.SubtitleStreams[i];
	sub.Deleted = true;
}

return 1;
```
Will update FFMPEG Builder: Start docs page with more information.  That node is required to be run before a function/script that uses this.

**Comment by revenz** [comment]
updated docs
